### ISSUE TITLE
Windows_path issue in Chef-Client 11.14.2

### ISSUE THREAD

**Issue by kpei** [chef-cookbooks/windows#105]
Getting an error of "Cannot modify env[PATH] - key does not exist!"

Full paste here http://pastebin.com/ctvVJHrz, anyone else getting the error as well on the new chef?  This wasn't happening when i ran it on an older version of Chef-Client (11.12.8 I believe)

**Comment by smurawski** [comment]
Chef 11.14.4 should have had the fix for this issue.
