### ISSUE TITLE
Installing package with other msiexec running in parallel fails run

### ISSUE THREAD

**Issue by chemikadze** [chef-cookbooks/windows#146]
If some other installation is in progress, msiexec finishes with exit code `1618` and message:
```
STDOUT: Another program is being installed. Please wait until that installation is complete, and then try installing this software again.
```
resulting resource run to fail.

Probably it would be better, if resource checked that exit code and retried several times with some graceful timeout.

**Comment by smurawski** [comment]
The `retries` common property supports this behavior for all resources.

https://docs.chef.io/resource_common.html#properties
