### ISSUE TITLE
How do I access the "installed?" method for the feature_servermanagercmd provider

### ISSUE THREAD

**Issue by vevo-dan-hoerst** [chef-cookbooks/windows#147]
If I run the following using servermanagercmd and the feature is already installed, the chef client will fail with an error noting that the feature is already installed.
```
windows_feature 'Web-Common-Http' do
  action :install
end
```
I see that the provider feature_servermanagercmd has a `installed?` method but I am unsure how to use it to first check if the feature is installed. Could someone give me a hand? Thanks.

**Comment by smurawski** [comment]
The resource should be checking for that feature ahead of trying to install it.  `installed?` is used by the resource internally.
