### ISSUE TITLE
Undefined method `checksum' for Chef::Resource::WindowsPackage with Chef 12.0.0

### ISSUE THREAD

**Issue by dhoer** [chef-cookbooks/windows#150]
This seems to be an issue with Chef 12.0.0 and windows_package (Windows Server 2012 R2):

```
10.168.18.67 [2014-12-05T17:45:15+00:00] INFO: *** Chef 12.0.0 ***
...
10.168.18.67 [2014-12-05T17:45:57+00:00] INFO: Loading cookbooks [sikulix_test@0.1.0, aws@2.5.0, java@1.29.0, windows@1.34.8, chef_handler@1.2.0, sikulix@2.0.0]
...
10.168.18.67 NoMethodError
10.168.18.67 -------------
10.168.18.67 undefined method `checksum' for Chef::Resource::WindowsPackage
10.168.18.67
10.168.18.67 Cookbook Trace:
10.168.18.67 ---------------
10.168.18.67   c:/chef/cache/cookbooks/java/recipes/windows.rb:73:in `block in from_file'
10.168.18.67   c:/chef/cache/cookbooks/java/recipes/windows.rb:71:in `from_file'
10.168.18.67   c:/chef/cache/cookbooks/java/recipes/default.rb:28:in `from_file'
10.168.18.67   c:/chef/cache/cookbooks/sikulix_test/recipes/default.rb:1:in `from_file'
10.168.18.67
10.168.18.67 Relevant File Content:
10.168.18.67 ----------------------
10.168.18.67 c:/chef/cache/cookbooks/java/recipes/windows.rb:
10.168.18.67
10.168.18.67  66:      action :add
10.168.18.67  67:    end
10.168.18.67  68:  end
10.168.18.67  69:
10.168.18.67  70:
10.168.18.67  71:  windows_package node['java']['windows']['package_name'] do
10.168.18.67  72:    source cache_file_path
10.168.18.67  73>>   checksum node['java']['windows']['checksum']
10.168.18.67  74:    action :install
10.168.18.67  75:    installer_type :custom
10.168.18.67  76:    options "/s #{additional_options}"
10.168.18.67  77:  end
```

**Comment by joelwilson** [comment]
@jdmundrawala I ran into this problem today. Maybe I'm missing something?

windows cookbook 1.36.1
chefdk 0.3.5
chefspec 



	================================================================================
	Recipe Compile Error in C:\Users\jwilson\AppData\Local\Temp\d20150121-3212-1thfwhm\cookbooks\xxx-java\recipes\default.rb
	================================================================================

	NoMethodError
	-------------
	undefined method `checksum' for Chef::Resource::WindowsPackage

	Cookbook Trace:
	---------------
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/resource.rb:295:in `method_missing'
	  C:\Users\jwilson\AppData\Local\Temp\d20150121-3212-1thfwhm\cookbooks\java\recipes\windows.rb:73:in `block in from_file'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/dsl/recipe.rb:119:in `instance_eval'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/dsl/recipe.rb:119:in `build_resource'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/dsl/recipe.rb:82:in `declare_resource'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/dsl/recipe.rb:42:in `method_missing'
	  C:\Users\jwilson\AppData\Local\Temp\d20150121-3212-1thfwhm\cookbooks\java\recipes\windows.rb:71:in `from_file'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/cookbook_version.rb:245:in `load_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:174:in `load_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:143:in `block in include_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:142:in `each'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:142:in `include_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
	  C:\Users\jwilson\AppData\Local\Temp\d20150121-3212-1thfwhm\cookbooks\java\recipes\default.rb:28:in `from_file'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/cookbook_version.rb:245:in `load_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:174:in `load_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:143:in `block in include_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:142:in `each'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:142:in `include_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
	  C:\Users\jwilson\AppData\Local\Temp\d20150121-3212-1thfwhm\cookbooks\xxx-java\recipes\default.rb:20:in `from_file'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/cookbook_version.rb:245:in `load_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:174:in `load_recipe'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/run_context.rb:97:in `load'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/client.rb:235:in `setup_run_context'
	  U:/.chefdk/gem/ruby/2.0.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:115:in `converge'
	  U:/.chefdk/gem/ruby/2.0.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:18:in `block in converge'
	  U:/.chefdk/gem/ruby/2.0.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:17:in `tap'
	  U:/.chefdk/gem/ruby/2.0.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:17:in `converge'
	  c:/SVN/cookbook-xxx-java/trunk/spec/default_spec.rb:4:in `block (2 levels) in <top (required)>'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/memoized_helpers.rb:242:in `block (2 levels) in let'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/memoized_helpers.rb:242:in `fetch'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/memoized_helpers.rb:242:in `block in let'
	  c:/SVN/cookbook-xxx-java/trunk/spec/default_spec.rb:7:in `block (2 levels) in <top (required)>'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `instance_exec'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `block in run'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:329:in `with_around_example_hooks'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:149:in `run'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:490:in `block in run_examples'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `map'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `run_examples'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:453:in `run'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block (2 levels) in run_specs'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `map'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block in run_specs'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	  C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	  C:/opscode/chefdk/embedded/bin/rspec:23:in `load'
	  C:/opscode/chefdk/embedded/bin/rspec:23:in `<main>'

	Relevant File Content:
	----------------------
	C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/chef-12.0.0.rc.0-x86-mingw32/lib/chef/resource.rb:

	288:      # If an unknown method is invoked, determine whether the enclosing Provider's
	289:      # lexical scope can fulfill the request. E.g. This happens when the Resource's
	290:      # block invokes new_resource.
	291:      def method_missing(method_symbol, *args, &block)
	292:        if enclosing_provider && enclosing_provider.respond_to?(method_symbol)
	293:          enclosing_provider.send(method_symbol, *args, &block)
	294:        else
	295>>         raise NoMethodError, "undefined method `#{method_symbol.to_s}' for #{self.class.to_s}"
	296:        end
	297:      end
	298:  
	299:      def load_prior_resource(resource_type, instance_name)
	300:        begin
	301:          key = ::Chef::ResourceCollection::ResourceSet.create_key(resource_type, instance_name)
	302:          prior_resource = run_context.resource_collection.lookup(key)
	303:          # if we get here, there is a prior resource (otherwise we'd have jumped
	304:          # to the rescue clause).

	F

	Failures:

	  1) xxx-java::default includes the java::default recipe
		 Failure/Error: let(:chef_run) { ChefSpec::SoloRunner.converge(described_recipe) }
		 NoMethodError:
		   undefined method `checksum' for Chef::Resource::WindowsPackage
		 # C:\Users\jwilson\AppData\Local\Temp\d20150121-3212-1thfwhm\cookbooks\java\recipes\windows.rb:73:in `block in from_file'
		 # C:\Users\jwilson\AppData\Local\Temp\d20150121-3212-1thfwhm\cookbooks\java\recipes\windows.rb:71:in `from_file'
		 # C:\Users\jwilson\AppData\Local\Temp\d20150121-3212-1thfwhm\cookbooks\java\recipes\default.rb:28:in `from_file'
		 # C:\Users\jwilson\AppData\Local\Temp\d20150121-3212-1thfwhm\cookbooks\xxx-java\recipes\default.rb:20:in `from_file'
		 # U:/.chefdk/gem/ruby/2.0.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:115:in `converge'
		 # U:/.chefdk/gem/ruby/2.0.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:18:in `block in converge'
		 # U:/.chefdk/gem/ruby/2.0.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:17:in `tap'
		 # U:/.chefdk/gem/ruby/2.0.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:17:in `converge'
		 # ./spec/default_spec.rb:4:in `block (2 levels) in <top (required)>'
		 # ./spec/default_spec.rb:7:in `block (2 levels) in <top (required)>'

	Finished in 3.12 seconds (files took 1 minute 19.93 seconds to load)
	1 example, 1 failure

	Failed examples:

	rspec ./spec/default_spec.rb:6 # xxx-java::default includes the java::default recipe

**Comment by jdmundrawala** [comment]
@joelwilson It looks like it is not loading the cookbook version. It's possible that ChefSpec does not like https://github.com/opscode-cookbooks/windows/blob/master/libraries/windows_package.rb#L223

**Comment by jdmundrawala** [comment]
Are you able to use any other resources that are in this cookbook and not in chef core?

**Comment by joelwilson** [comment]
I use windows_zipfile in a different cookbook. I'm not using the windows cookbook directly in this one - it uses the java cookbook.
https://supermarket.chef.io/cookbooks/java

It's strange - I can `vagrant up` a new box (chef solo) with no errors with the recipe under test. I just noticed though that I have it set to install chef version 11.16.4 via omnibus, but if I change it to `'latest'`, it installs 12.0.3 and provisioning still succeeds.

The recipe:

	if platform_family? 'windows'
	  node.set['java']['windows']['url'] = 'http://web/java64.exe'

	  unless ENV['Path'].include? node['javapath'] 
		ENV['Path'] = ENV['Path'] + ';' + node['javapath']
	  end
	end

	include_recipe 'java::default'

metadata.rb depends:

    depends 'windows', '~> 1.36.1' # for java (it is only suggested there)
    depends 'java', '~> 1.29.0'

**Comment by jdmundrawala** [comment]
Its possible there is some other bug in the version of chef 12 that shipped with chefdk 0.3.5.
You could try updating to chefdk 0.3.6, see if that solves anything

**Comment by jdmundrawala** [comment]
I think i figured it out:
https://github.com/opscode-cookbooks/windows/blob/master/libraries/windows_package.rb#L196

That line does not evaluate to true, and it needs to for chef 12. Upgrading to chefdk 0.3.6 should fix things

**Comment by joelwilson** [comment]
Awesome Jay. I will try it out tomorrow.

**Comment by joelwilson** [comment]
@jdmundrawala I'm not seeing the 0.3.6 ChefDK on chef.io for Windows. It shows up as an option for all other systems.

**Comment by jdmundrawala** [comment]
weird, maybe ctrl+f5 that page?

**Comment by joelwilson** [comment]
hah that did it - sorry I should have thought of that. I just assumed the cache would have expired by now.
