### ISSUE TITLE
windows_task 'cwd' attribute doesn't seem to work

### ISSUE THREAD

**Issue by kenny-evitt** [chef-cookbooks/windows#176]
My `windows_task` resource looks like this:

```
windows_task "Do something" do
  command "C:\\Apps\\Directory\\do-something.bat"
  cwd "C:\\Apps\\Directory"
  ...
  action [:create, :run]
end
```

When I inspect the action in the task in _Task Scheduler_ the _Start in (optional)_ field is blank.

**Comment by jdmundrawala** [comment]
schtasks does not have a way to set this. `cwd` does nothing...documentation is wrong.

cc @smurawski @btm

**Comment by smurawski** [comment]
@jdmundrawala @kenny-evitt We can set the working directory by building or modifying the xml representing the scheduled task - but that only works on Server 2008 and above.

**Comment by kenny-evitt** [comment]
@jdmundrawala @smurawski thanks for the quick reply. I guess the question now is whether `cwd` *should* be used, for the Windows versions that could support it. I'm inclined to answer that it should, but it seems like it's a relatively low priority feature.

I was just going to add a note to the README about the `cwd` attribute when I noticed this text under the section for the `windows_task` resource:

> Creates, deletes or runs a Windows scheduled task. Requires Windows Server 2008 due to API usage.

**Comment by jedugas** [comment]
Good example of 'the underlying tool is broken' ... so how about an 'xml' option for task file import, using an implementation something like this?

schtasks.exe /Create /XML the_task.xml /tn the_task_name { + other legit params }

Having a non-null xmlfile value (a path to a file) would necessarily supercede some of the other configuration options embedded.

**Comment by spuder** [comment]
I also got bit by this. While scheduled tasks does have a notion of 'start in' (atleast on 2012R2), the cookbook does not set this value. 

Looking at the source, the `cwd` attribute is only referenced once, and not in the place you would expect. 

https://github.com/opscode-cookbooks/windows/blob/master/providers/task.rb#L161

Opening a pull request to pull `cwd` from the docs.

**Comment by nwesoccer** [comment]
I believe this issue is causing a resource update every chef-client run.  The only difference in the initial and final state is the fact that cwd initial is '\' and final is ''.  However, this never updates, so this difference is always the case.

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
