### ISSUE TITLE
windows_task doesn't work at all on non-english windows

### ISSUE THREAD

**Issue by graf0** [chef-cookbooks/windows#179]
Hello!

This is output of schtasks /Query /FO LIST /V /TN "burp cron":

  Folder: \
  Nazwa hosta:                                        VAGRANT-BOX
  Nazwa zadania:                                      \burp cron
  Czas nast. uruchomienia:                            2015-02-12 16:00:00
  Stan:                                               Gotowe
  Tryb logowania:                                     Interakcyjne/W tle
  Czas ostat. uruchomienia:                           2015-02-12 15:40:00
  Ostatni wynik:                                      0
  Autor:                                              vagrant
  Zadanie do uruchomienia:                            "C:\Program Files\Burp\bin\burp.exe" -a t
  Rozpocznij w:                                       Brak
  Komentarz:                                          Brak
  Stan zaplanowanego zadania:                         Włączony
  Czas bezczynności:                                  Wyłączony
  Zarządzanie energią:                                Zatrzymaj w trybie zasilania bateryjnego, Nie uruchamiaj w trybie zasilania bateryjnego
  Uruchom jako użytkownik:                            SYSTEM
  Usuń zadanie, jeśli nie jest ponownie zaplanowane:  Włączony
  Zatrzymaj zadanie, jeśli działa X godzin i X minut: 72:00:00
  Harmonogram:                                        Dane planowania nie są dostępne w tym formacie.
  Zaplanowany typ:                                    Tylko raz, Co minutę
  Godzina rozpoczęcia:                                17:00:00
  Data rozpoczęcia:                                   2015-02-11
  Data zakończenia:                                   Brak
  dni:                                                Brak
  miesięcy:                                           Brak
  Powtórz: co:                                        0 godz., 20 min
  Powtórz do: godzina:                                Brak
  Powtórz do: czas trwania:                           Wyłączony
  Powtórz: zatrzymaj, jeśli wciąż uruchomione:        Wyłączony

So, there is no chance that task.rb provider will guess valid name. Efect - I get error, that task cannot be created, and even I see question, if I want to override (I cannot answer, but it's there).

I suspect this will be problem on any windows with language other, than english.

Possible solution:
- using ole api directory
- using xml mode

Any change to do something with that?

**Comment by cheeseplus** [comment]
Is this still an issue? I know there have been quite a few patches against chef-client and the winrm libs for handling non-english character sets so hoping we've fixed this over the course of time.

**Comment by graf0** [comment]
Hello!

No, it's resolved - windows_task is using xml output to detect info about existing tasks, so it's not prone to windows localization issues.

Cheers
