### ISSUE TITLE
windows_auto_run complains that registry_key should be used.

### ISSUE THREAD

**Issue by docwhat** [chef-cookbooks/windows#184]
When using `windows_auto_run` it complains:

```
WARN: Please use the registry_key resource in Chef Client 11. The windows_registry LWRP is still supported for Chef Client 10, but is deprecated in future versions.
```

I don't know if it is related (yet) but it also doesn't seem to be working for me... but I'm still researching that.

**Comment by ksubrama** [comment]
It internally uses the registry_key resource which pulls in the registry_key provider defined in this cookbook instead of the one from core chef.  When that provider is removed in the next major release, that warning should go away.

**Comment by tas50** [comment]
This should be fixed in the latest release
