### ISSUE TITLE
Add option to pass /quiet (instead of /norestart) when installing features with dism.exe

### ISSUE THREAD

**Issue by vuntz** [chef-cookbooks/windows#187]
Instead of having to deal with the restart ourselves, it's sometimes simpler to let dism.exe trigger the restart if needed. It seems that just passing /quiet (and removing /norestart) is enough.

cc @ovisan

**Comment by smurawski** [comment]
Actually, it's better to let Chef manage the reboot, so it can exit cleanly and log properly.  there is a native `reboot` resource in Chef and a `reboot_pending?` helper to check if a reboot has been requested by application or feature installs.
