### ISSUE TITLE
AppVeyor with automated tests

### ISSUE THREAD

**Issue by joelhandwell** [chef-cookbooks/windows#224]
Can [AppVeyor](http://www.appveyor.com/) be a consideration to test this cookbook?

**Comment by btm** [comment]
With a cookbook, we're mostly interested in testing that the changes it makes to the system are the ones we expect. Usually that means we run integration tests that modify the state of the system. So we need to test against instances that we can fully modify and then throw out. We've been doing that with test-kitchen locally.

There's been some effort to have Travis trigger test-kitchen to trigger ephemeral slaves in EC2 to run these kinds of tests over in the [chef client](https://github.com/chef/chef/blob/master/.travis.yml#L33). We've also talked about using something like [Buildkite](https://buildkite.com/) to trigger test-kitchen runs on bare metal in Chef HQ.

Other ideas are welcome.

**Comment by spuder** [comment]
This has been implemented. 

http://www.hurryupandwait.io/blog/run-kitchen-tests-in-travis-and-appveyor-using-the-kitchen-machine-driver

**Comment by mwrock** [comment]
Yup. Closing.
