### ISSUE TITLE
Windows_Package to install Java reboots the machine 

### ISSUE THREAD

**Issue by Infydevops** [chef-cookbooks/windows#239]
I am using Windows_Package to install Java 8 on my windows node with below code. Recently something got changed and during chef run the machine get rebooted. Though I have used /norestart but still machine is booted. 

-------------------------------------------------------------------------
include_recipe "windows::default"

if node['java'].attribute?("java_home")
  java_home_win = win_friendly_path(node['java']['java_home'])
  # The EXE installer expects escaped quotes, so we need to double escape
  # them here. The final string looks like :
  # /v"/qn INSTALLDIR=\"C:\Program Files\Java\""
  additional_options = "/v\"/qn /norestart INSTALLDIR=\\\"#{java_home_win}\\\"\""

  env "JAVA_HOME" do
    value java_home_win
  end

  # update path
  windows_path "#{java_home_win}\\bin" do
    action :add
  end
end

windows_package node['java']['windows']['package_name'] do
  source "http://10.66.110.227/jdk-8u45-windows-x64.exe"
  action :install
  installer_type :custom
  options "/s #{additional_options}"
end
-----------------------------------------------------------------

**Comment by smurawski** [comment]
The exact behavior of the java installer is dependent on it - not the windows_package resource.  The resource itself isn't causing the reboot.  The java installer may have a different switch to avoid a reboot, but that'll be specific to that installer.
