### ISSUE TITLE
windows_task should support random_delay property

### ISSUE THREAD

**Issue by pburkholder** [chef-cookbooks/windows#245]
@smurawski Per conversation on 15 July, would this be feasible to implement?

**Comment by smurawski** [comment]
Yes, it's non-trivial to implement though, so I won't have a chance to take a crack at it until September.

Anyone else is welcome though. ;)

**Comment by pburkholder** [comment]
Is this because `schtasks` will need to be replaced with something
PowerShellish?

On Wednesday, July 22, 2015, Steven Murawski <notifications@github.com>
wrote:

> Yes, it's non-trivial to implement though, so I won't have a chance to
> take a crack at it until September.
>
> Anyone else is welcome though. ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opscode-cookbooks/windows/issues/245#issuecomment-123737665>
> .
>


-- 

*Peter Burkholder* — Customer Success Engineer

Unavailability: Fully available early July....

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/pburkholder>  Twitter
<http://www.twitter.com/pburkholder>  Cal
<https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK>
endar

*CHEF*

CHEF.IO <http://www.chef.io/>

TM

*chef.io* <http://www.chef.io/>   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by smurawski** [comment]
No, we'll have to build xml for the scheduled job rather than use the default switches for schtasks.

**Comment by Annih** [comment]
Hello @smurawski 

I already created a new LWRP `Windows_advanced_task` in #255 which offers this feature using directly win32 api.
I assume that maybe it's not exactly what you want - 4 month past and still no feedback - but is there a way I can refactor my work to help you?

There are many issues and PR around `windows_task`, we really need to have something better than the schtasks wrapper.

Regards,

Annih

**Comment by smurawski** [comment]
@Annih Sorry for the delay in response, I've been on the road for much of this fall and haven't had time to really dig into your PR.  I'll be taking a look pretty soon, unless @mwrock or another @chef-cookbooks/windows-cookbook-collaborators gets to it first.

**Comment by NimishaS** [comment]
New property `random_delay` added in https://github.com/chef/chef/pull/5886. Accepted values are standard scheduled task input like: `PT5M` (for 5 min), `PT1H` (for 1 hr) etc.

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
