### ISSUE TITLE
windows_package fails for MSU files when using knife bootstrap

### ISSUE THREAD

**Issue by sebwerner** [chef-cookbooks/windows#249]
I noticed that windows_package fails when it tries to execute an MSU file during the first run of knife bootstrap. The recipe works fine during a regular run, but fails during the boostrap. 

    windows_package 'Windows Management Framework Core 5.0' do
      source 'c:\uscinstall\WindowsBlue-KB3055381-x64.msu'
      installer_type :custom
      options '/quiet /norestart'
      action :install
      success_codes [0, 42, 127, 3010]
      # Note that the :immediately is to immediately notify the other resource,
      # not to immediately reboot. The windows_reboot 'notifies' does that.
      #notifies :request, 'windows_reboot[powershell]', :immediately if reboot_pending? &&     node['powershell']['installation_reboot_mode'] != 'no_reboot'
      #not_if { registry_data_exists?('HKLM\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', { :name => 'PowerShellVersion', :type => :string, :data => '5.0.10105.0' }) }
    end

**Comment by smurawski** [comment]
@sebwerner Based on the windows security model, you cannot install MSU's in the WinRM context - https://support.microsoft.com/en-us/kb/2773898

In order to make this work, we'd have to unpack the MSU, and use DISM to install the cab file.
