### ISSUE TITLE
No resource, method, or local variable named `password' for `Chef::Provider::WindowsTask'

### ISSUE THREAD

**Issue by puneetloya** [chef-cookbooks/windows#256]
This is occuring only on 1.38+. 1.37.0 works smooth

**Comment by gyoza** [comment]
I am having this issue also... 1.38.1..

**Comment by piraxis** [comment]
This is still an issue in 1.38.2; however, I have only seen that happen on Windows Server 2008 R2. Windows Server 2012 R2 works fine for me. 

Currently the only workaround seems to be a revert to 1.37...

**Comment by mwrock** [comment]
I'm looking at changeset 971c7be0d9a46f929728174c9554f5bdc1536322 which seems like it would have introduced this. However, it seems like its not the OS that would cause this from happening but whether the `interactive_enabled` attribute is true. On your failing 2k8r2 converges, is that attribute set?

**Comment by piraxis** [comment]
@mwrock `interactive_enabled` is set to `true` on my failing converges for 2008r2.
