### ISSUE TITLE
windows_task failed with user name error

### ISSUE THREAD

**Issue by ABrehm264** [chef-cookbooks/windows#261]
Hey Guys, 

I just tried to update the windows cookbook from version 1.36.1 to 1.38.1 and I am getting the below error.

Error:
Mixlib::ShellOut::ShellCommandFailed: windows_task[\WindowsServerCleanup] (hps-windows::windows-server-cleanup-task line 34) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '-2147467259'
---- Begin output of schtasks /CREATE /TN "\WindowsServerCleanup" /F  /SC minute /MO 15 /TR "ruby c:\chef\scheduled-tasks\win_server_cleanup_scheduled_task.rb "c:\chef\scheduled-tasks\logs""  **/RU NT AUTHORITY\SYSTEM** /RL HIGHEST  ----
STDOUT: 
**STDERR: ERROR: Invalid argument/option - 'AUTHORITY\SYSTEM'.**
Type "SCHTASKS /CREATE /?" for usage.
---- End output of schtasks /CREATE /TN "\WindowsServerCleanup" /F  /SC minute /MO 15 /TR "ruby c:\chef\scheduled-tasks\win_server_cleanup_scheduled_task.rb "c:\chef\scheduled-tasks\logs""  /RU NT AUTHORITY\SYSTEM /RL HIGHEST  ----
Ran schtasks /CREATE /TN "\WindowsServerCleanup" /F  /SC minute /MO 15 /TR "ruby c:\chef\scheduled-tasks\win_server_cleanup_scheduled_task.rb "c:\chef\scheduled-tasks\logs""  /RU NT AUTHORITY\SYSTEM /RL HIGHEST  returned -2147467259

Looks like it was introduced with this commit. 99898c3e9d58afe0a0cd2c1927a19fde7db3dabf

Can someone please look into this?

**Comment by jeremymv2** [comment]
I'm seeing the same issue as well.  This is currently breaking one of my Chef environments.

**Comment by Tech356** [comment]
I just ran into the same thing. The username is no longer quoted when being passed. So usernames with spaces in them fail. Like "NT AUTHORITY\SYSTEM". Commit 99898c3 also stopped quoting the arguments for ST, SD, and RP.

**Comment by mwrock** [comment]
#310 should fix this
