### ISSUE TITLE
provider Chef::Provider::WindowsFeaturePowershell

### ISSUE THREAD

**Issue by ajeba99** [chef-cookbooks/windows#264]
According to the README in order to install a feature using powershell I need to use in my recipe ...
````
windows_feature 'Net-Framework-Core' do
  provider Chef::Provider::WindowsFeaturePowershell
  action :install
  all true
end
````
However, when I do so, I get ...
````
[2015-08-18T17:17:06+00:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supporte
d in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-18T17:17:06+00:00] WARN: Using an LWRP provider by its name (WindowsFeaturePowershell) directly is no longer su
````
At what point will this cookbook go to using "Chef::ProviderResolver.new(node, resource, action) instead" ?  If it is, how do I do that?

**Comment by spuder** [comment]
I'm also finding that WindowsFeaturePowershell is not implemented (search the source for it, 0 results). 

The link in the documentation points to the deprecated JIRA, and login credentials no longer work. https://tickets.chef.io/browse/COOK-3714

**Comment by spuder** [comment]
Try this syntax, works for me

```
windows_feature "smtp-server" do
  action :install
  all true
  provider :windows_feature_powershell
end
```


As for Net-Framework-Core, here is how I install it (using the dism.exe names, not the get-windowfeature names. 

```ruby
windows_feature 'IIS-ASPNET45' do
  action :install
  all true
end

windows_feature 'AS-NET-Framework' do
  action :install
end

windows_feature 'IIS-NetFxExtensibility45' do
  action :install
end
```

**Comment by ajeba99** [comment]
Please don't misunderstand me, I can get it installed.  I'm just wondering when the warnings will get resolved.

**Comment by nhudacin** [comment]
Same here... I can get the windows features installed by that warning concerns me. 

```
[2015-08-18T17:17:06+00:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supporte
d in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-08-18T17:17:06+00:00] WARN: Using an LWRP provider by its name (WindowsFeaturePowershell) directly is no longer su
```

What is the correct syntax? Maybe this is a problem with the windows cookbook and not an issue with the consumers?

**Comment by vvchik** [comment]
+1 for this.

**Comment by ajeba99** [comment]
There isn't a supported Windows OS that doesn't come with Powershell now.  It should be the default.

**Comment by mwrock** [comment]
One thing to be aware of is that the powershell provider uses the ServerManager module which is not installed on client SKUs. While it is certainly more common for users to converge server SKUs with chef, there are some who use chef to setup client OSs (win7, 8, 10) and if they use this resource, defaulting to the powershell provider would break them. DISM, while somewhat evil, works everywhere.

**Comment by jonnyyu** [comment]
I met the exact same message, could you add or update examples to shows how to use the new approach? thanks!

**Comment by ajeba99** [comment]
@mwrock So what you're saying is this is a Chef bug/request because the Powershell Provider was written to require Server Manager instead of just calling a script with powershell.exe?

**Comment by smurawski** [comment]
@ajeba99 No. As things stand in the windows ecosystem today, the powershell provider will only work for Server SKUs.  The only way to install optional features on Windows clients SKUs is DISM.  Windows 8.1 introduced Enable-WindowsOptionalFeature in PowerShell but that still requires the DISM version of the feature name, so you wouldn't gain anything over the existing DISM provider by calling it from PowerShell.

**Comment by ajeba99** [comment]
Ok, thanks.

**Comment by shoekstra** [comment]
Hi,

This issue has been closed and there is no feedback regarding the warnings.

As @nhudacin said, 
> What is the correct syntax? Maybe this is a problem with the windows cookbook and not an issue with the consumers?

Re correct syntax, I receive the same whether using `provider :windows_feature_powershell` or `provider Chef::Provider::WindowsFeaturePowershell`, so I'm guessing it's the latter and a problem with the windows cookbook?

**Comment by mwrock** [comment]
The warnings here are really not the fault of syntax in consuming cookbooks. Rather, they are a result of how the providers are being assigned to the resources in the windows cookbook implementation. This resource/provider abstraction needs to be refactored to comply with the current state of custom resources.

**Comment by ajeba99** [comment]
@mwrock  So this goes full circle back to my original question ...

````
At what point will this cookbook go to using "Chef::ProviderResolver.new(node, resource, action) instead" ?
````
If it requires a refactor, when will that happen?  Is it on the road map any time soon?

**Comment by mwrock** [comment]
sorry I should have referenced the other issue that I was using to track this since it targeted the actual root more specifically. That is #273. I'm gonna reclose this but dont take that to mean its not tracked.

I really can't answer as to when it will be fixed. I and others would like to gradually move many of the resources from this cookbook over to the core chef client and refactor as that work is done. The windows_package resource is a good example of a recent migration.

**Comment by ajeba99** [comment]
Thank You.
