### ISSUE TITLE
passing variable to windows_task resource

### ISSUE THREAD

**Issue by trekr5** [chef-cookbooks/windows#266]
Hi everyone,

I'm hoping someone can help me.

I have a scheduled task that will run every 15 minutes and delete files that are older than 2 minutes.

This is the code I use:-

     pass_day = "Z:\\s3_temp\\#{Time.now.strftime("%Y-%m-%d")}" 
        windows_task 'deletion-of-logs-every-fifteen-minutes' do
          user 'Administrator'
          cwd pass_day
          command "powershell.exe Get-ChildItem  #{passday} | Where-Object {$_.LastwriteTime -lt     (Get-Date).addMinutes(-2) } | Remove-Item -Recurse -Force"
          run_level :highest
          frequency :minute
          frequency_modifier 15
          force true
          action :create
    end

However when this runs, it doesn't complete successfully (i.e. the files in Z:\s3_temp\2015-08-10) do not get deleted.

How would I do this to pass the variable pass_day into this resource as pass_day will change every day?

Many thanks

**Comment by Tech356** [comment]
Does the task complete successful but the files aren't deleted? Or does the task error? If the task errors, what is the error?

I noticed that you don't have a password specified. I think you need that to use a non-system account.

**Comment by trekr5** [comment]
Hi,
The task does not complete successfully (the status of it is not equal to 0) and obviously the files aren't deleted.

I'm trying to delete files that are locked by a process for a short period and then released. What I find interesting is that I'm able to delete these files on the command line, after they have been released, but can't from within a script using the windows_cookbook resource.

Because the file is publicly viewable (i.e. in a git repo), I would be unable to include the plaintext password as part of the resource, (although I realise that it could be encrypted).

Does the syntax look right to you?

**Comment by Tech356** [comment]
What is the task error? In task scheduler, the "Last Run Result" should have an error. Have you inspected the task in the task scheduler after it was created to verify all the commands and triggers are correct?

I wouldn't expect you to post the actual password. Something like `password 'mypassowordgoeshere'` is enough to let us know that you are using a password in your resource. 

The syntax looks correct except for the use of `pass_day` and `passday`. I assume you want an underscore in the second one.

**Comment by chrisgit** [comment]
@trekr5 It sounds more like a schedule task/powershell command issue, have you written a schedule task that works? Does the schedule task manage to call the powershell.exe? What does the correctly configured Schedule Task look like?

We tend to build everything manually first then automate that, however a backslash is a metacharacter for both Ruby and Powershell so we always end up doubling the number backslashes!

**Comment by mwrock** [comment]
Its also worth hopping onto the node and looking at the scheduled task that was created. In particular look at the command text and make sure it is formed as you expected. From there, definitely follow @chrisgit 's guidance and run the command to troubleshoot where things are wrong.

**Comment by mwrock** [comment]
I'm closing here since this is likely not a problem in the cookbook.
