### ISSUE TITLE
Warning in windows_feature resource with chef client version 12.4.1

### ISSUE THREAD

**Issue by pbobov** [chef-cookbooks/windows#273]
windows_feature resource generates warning log message with chef client version 12.4.1:

```
WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.
```

**Comment by jedugas** [comment]
Same for the latest ChefDK (0.10.0) which uses chef client 12.5.1  ...

https://www.chef.io/blog/2015/02/10/chef-12-provider-resolver/

**Comment by krisdas73** [comment]
I am seeing the same issue. Is there any workaround to atleast the suppress the warning, till we have a fix?

**Comment by tas50** [comment]
We're working on a fix for this one. Thanks for the report.

**Comment by stonesbg** [comment]
Is there a time frame on when this bug might be fixed.  Based on the [Preparing for Chef 13](https://blog.chef.io/2017/01/30/preparing-for-chef-13/) i have changed test kitchen to flag the warnings as error and this bug is being picked up

**Comment by tas50** [comment]
We've reworked the windows feature LWRP as a custom resource and eliminated this warning. We'll soon ship version 3.0.0 of this cookbook with that new resource.
