### ISSUE TITLE
windows_zipfile use powershell 3 when available

### ISSUE THREAD

**Issue by dhoer** [chef-cookbooks/windows#279]
Rubyzip has performance problems that has caused [failure to allocate memory](https://github.com/rubyzip/rubyzip/issues/233#issuecomment-135932035) when deflating.  I worked around this issue by using powershell's [compression lib](https://github.com/dhoer/chef-iedriver/blob/master/recipes/default.rb#L12-L18) when powershell [3 or greater is installed](https://github.com/dhoer/chef-iedriver/blob/master/libraries/default.rb#L5-L11).   

 I have to repeat this code a lot. Would there be interest in merging this approach into Windows cookbook if I submit a pull request? If not, I could create windows_zip cookbook with this functionality.  

P.S. I know 7-zip is available, but I like to use native libs when available.

**Comment by Tech356** [comment]
I think this would be a good addition. I like using native tools when possible.

**Comment by dhoer** [comment]
With the addition of powershell_script in Chef 12, I don't think unzip is needed anymore. You can just use powershell, e.g., 

    powershell_script "unzip #{filename}" do
      code "Add-Type -A 'System.IO.Compression.FileSystem';" \
        " [IO.Compression.ZipFile]::ExtractToDirectory('#{cached_file}', '#{new_resource.path}');"
      action :nothing
      notifies(:run, "batch[install #{new_resource.servicename} service]", :immediately)
    end
