### ISSUE TITLE
Add ability to add certificates to the Web Hosting store

### ISSUE THREAD

**Issue by pvandervelde** [chef-cookbooks/windows#297]
The windows_certificate and windows_certificate_binding recipes only allow connecting to the MY, ROOT and CA stores. It would be useful to have the ability to add to the WebHosting store as well.

**Comment by bogdanvarlamov** [comment]
Also the the store_name is restricted only to MY, ROOT, CA stores... why?

attribute :store_name, kind_of: String, default: 'MY', regex: /^(?:MY|CA|ROOT)$/

Can I not use the web hosting store in binding? https://github.com/chef-cookbooks/windows/blob/master/resources/certificate_binding.rb

**Comment by ruicovelo** [comment]
I need WebHosting too. I am adding to the regex in my fork but would be nice to know if the regex is need at all. Why not leave that to the resource user?

**Comment by smurawski** [comment]
@chef-cookbooks/windows-cookbook-collaborators @chef-cookbooks/client-windows

**Comment by mwrock** [comment]
Seems like we should remove the regex or at least not limit to specific folders. Different windows will have different folders and its difficult to reliably state all the possibilities.

**Comment by tas50** [comment]
This should be resolved in the latest version of the cookbook which uses and updated version of our win32-certstore gem. If you're still having this issue after updating the cookbook then please open this back up so we can dig in.
