### ISSUE TITLE
windows_task support for Months and frequency modifier strings for first, second, etc...

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/windows#304]
windows_task needs support for months (schtasks /create /M) and frequency modifier to accept strings for (first, second, third, etc...). This allows companies like ours to create tasks for scheduling stuff like patches on 3rd tuesday of all months except december due to the holidays.

**Comment by Stromweld** [comment]
@mwrock what would be the next steps to try and get this pull request integrated into the next release of the windows cookbook?

I am currently using our fork of this cookbook with this patch on all of our production windows 2008, windows 2008r2, windows 2012+ machine for sheduling a patch script to run. This also enhances the windows_tasks resource to fully support selection of months as well as all frequency modifiers for monthly, weekly, etc...

**Comment by mwrock** [comment]
Hey thanks for the PR! I just added some comments there.
