### ISSUE TITLE
windows_task ignores cwd option

### ISSUE THREAD

**Issue by zdenko-s** [chef-cookbooks/windows#309]
Create task and specify cwd option:
windows_task 'chef-client' do
  cwd 'C:\\temp'
  command 'C:\\opscode\\chef\\bin\\chef-client.bat'
end
Export created task. Here is part of XML
    <Exec>
      <Command>C:\opscode\chef\bin\chef-client.bat</Command>
    </Exec>
Edit task using Task Scheduler GUI and specify working directory. Export task again and compare XML.
    <Exec>
      <Command>C:\opscode\chef\bin\chef-client.bat</Command>
      <WorkingDirectory>c:\temp</WorkingDirectory>
    </Exec>
Working directory element is present

**Comment by mwrock** [comment]
#311 should fix this

**Comment by spuder** [comment]
https://github.com/chef-cookbooks/windows/issues/176
