### ISSUE TITLE
Unable to create windows scheduled task.  Chef errors with "<?" on UTF-16

### ISSUE THREAD

**Issue by christianclarke** [chef-cookbooks/windows#322]
Hello.

Attempting to create a Windows Scheduled task.  Currently using Chef-client 11.18.6 and the Windows 1.39.0 cookbook.  

Below is the basic testcode that I used to create a Schedule Task.

include_recipe 'windows'

file 'c:\users\vagrant\documents\runme.bat' do
  content 'echo this is the time %time% > myfile.txt'  
  action :create
end

windows_task "mytesttask" do  
  user 'SYSTEM'
  cwd 'C:\Users\Vagrant\Documents'
  command 'runme.bat'
  run_level :highest
  frequency :once
  start_time (::Time.now + 1).strftime('%H:%M')
  action :create
end

Creating a Scheduled task with Windows cookbook 1.38.4 & Chef-Client 11.18.6 works perfectly.  However, run the same code with the Windows cookbook 1.39.0 and Chef fails to converge with the below error.

Below is the error output.  

    ============================================================================
====
    Error executing action `create` on resource 'windows_task[\mytesttask]'
    ============================================================================
====

    Encoding::InvalidByteSequenceError
    ----------------------------------
    "<?" on UTF-16

    Resource Declaration:
    ---------------------
    # In C:/Users/vagrant/.chef/local-mode-cache/cache/cookbooks/nvm_ms_dotnet/r
ecipes/default.rb

     28: windows_task "mytesttask" do
     29:   user 'SYSTEM'
     30:   cwd 'C:\Users\Vagrant\Documents'
     31:   command 'runme.bat'
     32:   run_level :highest
     33:   frequency :once
     34:   start_time (::Time.now + 1).strftime('%H:%M')
     35:   action :create
     36: end

    Compiled Resource:
    ------------------
    # Declared in C:/Users/vagrant/.chef/local-mode-cache/cache/cookbooks/nvm_ms
_dotnet/recipes/default.rb:28:in `from_file'

    windows_task("\mytesttask") do
      action [:create]
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name "nvm_ms_dotnet"
      recipe_name "default"
      user "SYSTEM"
      cwd "C:\\Users\\Vagrant\\Documents"
      command "runme.bat"
      run_level :highest
      frequency :once
      start_time "16:01"
      task_name "\\mytesttask"
      frequency_modifier 1
    end

The stacktrace is below.

Generated at 2016-01-04 16:01:23 +0000
Encoding::InvalidByteSequenceError: windows_task[\mytesttask] (nvm_ms_dotnet::default line 28) had an error: Encoding::InvalidByteSequenceError: "<?" on UTF-16
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/encoding.rb:41:in `encode'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/encoding.rb:41:in `decode'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:58:in `encoding='
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:46:in `initialize'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:162:in `initialize'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:17:in `new'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:17:in `create_from'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:127:in `stream='
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:116:in `initialize'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:9:in `new'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:9:in `initialize'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/document.rb:245:in `new'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/document.rb:245:in `build'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/document.rb:43:in `initialize'
C:/Users/vagrant/.chef/local-mode-cache/cache/cookbooks/windows/providers/task.rb:197:in `new'
C:/Users/vagrant/.chef/local-mode-cache/cache/cookbooks/windows/providers/task.rb:197:in `set_cwd'
C:/Users/vagrant/.chef/local-mode-cache/cache/cookbooks/windows/providers/task.rb:55:in `block in class_from_file'

I did some manual investigation.  By following the above stack trace in the Windows\providers\task.rb

def set_cwd(folder)
  Chef::Log.debug 'looking for existing tasks'
  xml_cmd = shell_out("schtasks /Query /TN \"#{@new_resource.task_name}\" /XML")
  return if xml_cmd.exitstatus != 0
  doc = REXML::Document.new(xml_cmd.stdout)

On my VM I ran "schtasks" manually to create an XML structure.  When I attempted to create an instance from the REXML::Document class it reproduced the very same stacktrace.

C:\Users\vagrant>SCHTASKS /Query /TN \Microsoft\Windows\Wininet\CacheTask /XML
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task
">
  <RegistrationInfo>
    <Author>$(@%systemroot%\system32\wininet.dll,-16000)</Author>
    <Description>$(@%systemroot%\system32\wininet.dll,-16001)</Description>
    <URI>\Microsoft\Windows\Wininet\CacheTask</URI>
    <SecurityDescriptor>D:P(A;;FA;;;BA)(A;;FA;;;SY)(A;;0x001200a9;;;BU)(A;;0x001
200a9;;;WD)(A;;0x001200a9;;;LW)</SecurityDescriptor>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="AnyUser">
      <GroupId>S-1-5-32-545</GroupId>
    </Principal>
  </Principals>
  <Settings>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
    <MultipleInstancesPolicy>Parallel</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="AnyUser">
    <ComHandler>
      <ClassId>{0358b920-0ac7-461f-98f4-58e32cd89148}</ClassId>
    </ComHandler>
  </Actions>
</Task>
C:\Users\vagrant>SCHTASKS /Query /TN \Microsoft\Windows\Wininet\CacheTask /XML >
 taskxml.xml

C:\Users\vagrant>irb
irb(main):001:0> require 'rexml/document'
=> true
irb(main):002:0> myxmlfile = File.new("taskxml.xml")
=> #<File:taskxml.xml>
irb(main):003:0> doc = REXML::Document.new(myxmlfile)
Encoding::InvalidByteSequenceError: "<?" on UTF-16
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/encoding.rb:41:in `en
code'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/encoding.rb:41:in `de
code'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:58:in `enco
ding='
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:46:in `init
ialize'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:162:in `ini
tialize'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:14:in `new'

        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:14:in `crea
te_from'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/baseparser.rb
:127:in `stream='
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/baseparser.rb
:116:in `initialize'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/treeparser.rb
:9:in `new'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/treeparser.rb
:9:in `initialize'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/document.rb:245:in `n
ew'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/document.rb:245:in `b
uild'
        from C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/document.rb:43:in `in
itialize'
        from (irb):3:in `new'
        from (irb):3
        from C:/opscode/chef/embedded/bin/irb:12:in `<main>'irb(main):004:0>

**Comment by mwrock** [comment]
Yeah this used to work because the `cwd` attribute used to not do anything. Now we edit the task xml to change the working directory. I'm guessing that this is related to the fact that your system may be using a codepage emitting non UTF-16 characters.

Would you mind running `chcp` and responding with the codepage your system is running?

You can avoid this by ommiting the `cwd` attribute if thats not needed.

**Comment by christianclarke** [comment]
Hello Matt.

Ran the chcp command, the Active code page: 437

Thanks,
Christian

**Comment by mwrock** [comment]
@christianclarke hmm. Well thats the same codepage as I have. Would you mind either emailing me that xml file or putting it on a publicly accessible place? It really sounds like there is something specific to your system encoding the output of schtasks in an incompatible manner and I'd like to try fiddling with it to see if we can convert it propperly.

**Comment by christianclarke** [comment]
@mwrock Hello.  Just replied to you're email.  I shared a folder and physically copied the XML file from my Guest to Host.  I also checked that I still could reproduce the error.  I was able to.

If you need anything else to help debug, please ping me.  We can arrange a Skype chat/screen share etc & I can spin up a local TestKitchen Windows VM to demo it to you.

Thank you!
Christian Clarke

**Comment by christianclarke** [comment]
@mwrock Hello.  Just replied to you're followup email. 

The packer built Windows VM Box that we use for Test Kitchen is:

The Windows OS is Windows Server 2012 Standard.  
When using the “ver” command – the output is 6.2.9200

Verfied via Control Panel > Clock, Language, and Region

Region >  is set to United States.
Language > is set to English (United States)

I think you are right that’s it’s the Windows VM that’s the cause, because a colleague of mine has encountered the same problem with Windows cookbook : creating schedule task .. and he’s using the same image.

Could it be the version of Ruby ?  We’re using Chef-Client 11.18.6.  I shall attempt to reproduce with Chef-Client 12.x.

Thanks!
Christian Clarke

**Comment by mwrock** [comment]
Yeah I have been testing against 12 and on windows 10 and 2012R2. I dont have a 2012 standard image handy but can certainly test on older ruby. will report back.

**Comment by mwrock** [comment]
sweet! I can reproduce in ruby 1.9.3.

**Comment by mwrock** [comment]
probably not going to pursue this further since it only occurs on chef 11 and we are well into chef 12. There are a couple workarounds: upgrade or avoid the `cwd` attribute.
