### ISSUE TITLE
Fail to load to the Chef server: windows/spec/default_spec.rb:8: syntax error, unexpected ':', expecting ')'

### ISSUE THREAD

**Issue by OrionBill** [chef-cookbooks/windows#334]
Hello,
I would like to know, what is the issue? Does version 1.39.1 depend on particular Chef server/Ruby version?

My Server:
chef-server-cookbooks   11.0.12
chef-server-ctl         11.0.12
chef-server-scripts     11.0.12
ruby                    1.9.3-p484 
rubygems                1.8.24

When I loaded the cookbook to Chef server, it show this

Uploading windows        [1.39.1]
FATAL: Cookbook file spec/default_spec.rb has a ruby syntax error:
FATAL: /tmp/windows/spec/default_spec.rb:8: syntax error, unexpected ':', expecting ')'
FATAL: ...hef_gem(win_gem).with(options: '--platform=mswin32')
FATAL:                               ^
FATAL: /tmp/windows/spec/default_spec.rb:8: syntax error, unexpected ')', expecting kEND
FATAL: /tmp/windows/spec/default_spec.rb:12: syntax error, unexpected kDO_BLOCK, expecting kEND
FATAL: ...32-event win32-mutex ).each do |win_gem|
FATAL:                               ^
FATAL: /tmp/windows/spec/default_spec.rb:13: syntax error, unexpected tSTRING_BEG, expecting kDO or '{' or '('
FATAL:     it "installes #{win_gem} gem" do
FATAL:         ^
FATAL: /tmp/windows/spec/default_spec.rb:13: syntax error, unexpected kDO_BLOCK, expecting kEND
completed

Thanks.

**Comment by mwrock** [comment]
weird. seems to be broken by the hash key, but the jason style hash keys were introduced in ruby 1.9.

**Comment by tas50** [comment]
We're currently requiring Chef 12.1+ for this cookbook in the 2.X releases. ChefDK and Chef both ship with Ruby 2+ (2.3.1 currently) so any hash issues should be resolved at this point.
