### ISSUE TITLE
Version library identifies Windows 8.1 as Windows Server 2012 R2

### ISSUE THREAD

**Issue by FreakyDug** [chef-cookbooks/windows#335]
I am running the sensu cookbook (https://github.com/sensu/sensu-chef) which uses the Windows cookbook's version library (https://github.com/chef-cookbooks/windows/blob/master/libraries/version.rb) to detect Windows Server 2012 so it can install .NET 2.5 correctly.

Unfortunately, the version library doesn't know about Windows 8.1, so it seems to be misclassifying it as Windows Server 2012 R2. It also doesn't know about Windows 10, but I don't know what it classifies it as, because I haven't tried it.

**Comment by mwrock** [comment]
Yeah they should really be using [`Chef::ReservedNames::Win32::Version`](https://github.com/chef/chef/blob/master/lib/chef/win32/version.rb). win 8.1 has been in there for quite some time now. Windows 10 is currently wrong but has been corrected for the upcoming release.

**Comment by tas50** [comment]
Closing this as the built in methods in chef should be used
