### ISSUE TITLE
SNI: Server Name Indication support

### ISSUE THREAD

**Issue by ruicovelo** [chef-cookbooks/windows#337]
Is there anyone working on SNI support for the certificate_binding provider or anything planned?

If not, I am going to implement it myself. Is there any interest in having this merged into the windows cookbook? Are there any guidelines I should follow to have this eventually merged to the windows cookbook besides https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD? 

As far as my quick research led me to understand, I can keep using netsh to create the binding but I will be using powershell to configure server name indication flag. Does this seem ok?

**Comment by mwrock** [comment]
Sounds good. The powershell just needs to be v2 compatible.

**Comment by ruicovelo** [comment]
It should work with Powershell v2. But it does required WebAdministration module which I think is only available (or fully available) for Windows 2008 R2. I can't find a reference at the moment. Can search later. 

Is that a problem?

**Comment by ruicovelo** [comment]
Question 2:

If I am understanding correctly, the current implementation only associates a certificate to an already existing web binding. If the web binding does not exist, nothing happens.

Is this deliberate or can I add the code to create the web binding?

**Comment by mwrock** [comment]
That sounds right @ruicovelo. You might want to look at [the IIS cookbook](https://github.com/chef-cookbooks/iis) for what you are trying to do. That may have already implemented this.

**Comment by ruicovelo** [comment]
By reading the code, seems likely. I'm going to test it and I'll close this issue if I confirm that. Thank you for the tip!

**Comment by ruicovelo** [comment]
Ok. IIS cookbook does not support it yet but they are also interested in having that in. I think it makes more sense to add that to the iis cookbook.
