### ISSUE TITLE
windows_task fails to send 'notify' to other resources

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/windows#342]
If you have a windows_task resource, and you attempt to 'notify' another resource, nothing will happen. 

```ruby
# Here the c:\\notifytest.txt file is never created

file 'c:\\notifytest.txt' do
  action :nothing
end

windows_task 'say hi' do
  user 'SYSTEM'
  command 'echo hello'
  run_level :highest
  frequency :onstart
  notifies :create, 'file[c:\\notifytest.txt]', :immediately
  action :create
end
```

**Comment by mwrock** [comment]
I think the issue here is the quoting of the file name. If you change the recipe to:
```
file 'c:/notifytest.txt' do
  action :create
end

windows_task 'say hi' do
  user 'SYSTEM'
  command 'echo hello'
  run_level :highest
  frequency :onstart
  notifies :create, 'file[c:/notifytest.txt]', :immediately
  action :create
end
```
It works.

Single quotes in ruby will render `'\\'` as exactly `\\` and not `\\`. You want to either use double quotes , single quotes and one backslash or just use a forward slash.

I'd say we could use some better error handling/messaging, but the problem is not related to the task resource.

**Comment by spuder** [comment]
Thanks for looking at that. The above example isn't the best. Here are 2 more examples that also reproduce this

chef 12.7.2
Windows 2012R2


Here, neither the registry key, nor the text file are created
 
     chef-client -z -r 'recipe[foo::bar]' -c C:\chef\myconfig.rb

```ruby
warning_caption = 'herpderp'
warning_text = 'foobar'
warning_key = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'

registry_key 'derp' do
  key warning_key
  values [
    {:name => 'legalnoticecaption', :type => :string, :data => warning_caption},
    {:name => 'legalnoticetext', :type => :string, :data => warning_text}
  ]
  action :nothing
end

file 'c:/notifytest.txt' do
  action :nothing
end

# Fails to send the notify
windows_task 'chef ad-join' do
  user 'SYSTEM'
  command 'chef-client -L C:\chef\chef-ad-join.log'
  run_level :highest
  frequency :onstart
  notifies :create, 'registry_key[derp]', :immediately  #Not working
  notifies :create, 'file[c:/notifytest.txt]', :immediately #Not working
  action :create
end
```

However if I use any other resource, like `ruby_block` both the registry keys and the file are created successfully. 

```ruby
warning_caption = 'herpderp'
warning_text = 'foobar'
warning_key = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'


registry_key 'derp' do
  key warning_key
  values [
    {:name => 'legalnoticecaption', :type => :string, :data => warning_caption},
    {:name => 'legalnoticetext', :type => :string, :data => warning_text}
  ]
  action :nothing
end

file 'c:/notifytest.txt' do
  action :nothing
end

ruby_block 'foo' do
  block do
    puts "hey"
  end
  notifies :create, 'registry_key[derp]', :immediately #Success
  notifies :create, 'file[c:/notifytest.txt]', :immediately #Success
end
```

I'm using chef-zero to test this. I also find the same behavior with chef-client. I still think there is something else going. It seems like the :create action on the windows_task provider doesn't modify 'updated_by_last_action'

**Comment by chrisgit** [comment]
Hi, I responded to your previous log of this issue here

https://github.com/chef-cookbooks/windows/issues/271

The resource name is being changed by the code in the windows_task provider! 

You need to specify a task_name.

**Comment by spuder** [comment]
Indeed this is my own duplicate. I'll close this issue and move the conversation back to 271. 

Solution: You do need to have a 'task_name'
