### ISSUE TITLE
windows_package requires 'source' attribute on :remove action

### ISSUE THREAD

**Issue by Valiev** [chef-cookbooks/windows#343]
`windows_package` requires `source` attribute on `:remove` action.

**Comment by mwrock** [comment]
Yes that's not ideal. If you are on chef client v12.6 or above, it's package resource does not require it on remove.

**Comment by Valiev** [comment]
The problem still persists in chef client v12.6.0 and v12.7.x  using `windows` cookbook.

**Comment by mwrock** [comment]
You can get around it by using `package` instead of `windows_package`

**Comment by Valiev** [comment]
@mwrock sound like a workaround. Will try it out. Thanks!

**Comment by tas50** [comment]
I'm closing this out since we've removed the windows_package from the windows cookbook altogether now
