### ISSUE TITLE
Chef Client 12.7.2 fails on windows-pr gem

### ISSUE THREAD

**Issue by Tech356** [chef-cookbooks/windows#345]
My chef runs are now breaking since windows-pr is no longer installed and the client cannot contact the internet to download the gem. 

https://github.com/chef/chef/commit/828847d322c3e8239a73c5615b323c28ded4ad03

Does this cookbook depend on the windows-pr gem still? Is there a plan to make the same dependency changes to this cookbook to bring it inline with the chef client again? Or do I need to figure out a way to provide the windows-pr gem to my nodes?

**Comment by mwrock** [comment]
Looks like windows-pr is still used by `windows_privileged`

**Comment by tas50** [comment]
We've removed these gems from the default recipe on master. If you need any additional gems that aren't provided in the chef installer you can install them using chef_gem.
