### ISSUE TITLE
Feature: font LWRP should allow a configurable source

### ISSUE THREAD

**Issue by joemillerr** [chef-cookbooks/windows#363]
### Cookbook version

1.40.0
### Chef-client version

12.9.38
### Platform Details

Windows Server 2012 R2
### Scenario:

I want to use my own artifact repo to ship fonts, not the files directory in the cookbook.

**Comment by KierranM** [comment]
It would be great if this supported sources other than local files

**Comment by tas50** [comment]
This has been shipped. Enjoy
