### ISSUE TITLE
Task only looks at command and user for idempotency check

### ISSUE THREAD

**Issue by mwrock** [chef-cookbooks/windows#366]
Currently the `windows_task` resource checks the `command` text and the `user` for changes to determine whether or not to reconverge. Any change to the frequency modifiers and other attributes will not regenerate the task.

**Comment by NimishaS** [comment]
@mwrock, @btm  I observed that if I try to create a task using `windows_task` resource with a name which is already existing and different `command`, the existing task gets overwritten. So for the user, it's like the existing task is getting modified.
We have a `change` action too which should ideally be used for modifying an existing task (however it is also not currently modifying the attributes like frequency, frequency_modifier etc).
So the question is if we should allow `create` action to modify an existing task? Or should we raise an error saying `A task with the given name already exist. Please use :change action if you want to modify it`?

**Comment by mwrock** [comment]
My inclination would be to eliminate the `change` action and only use `create` which would modify the task if an attribute is altered. I'd leave this cookbook resource alone - it will be deprecated anyways - and make sure the task in chef core uses this new behavior.

**Comment by suchakra** [comment]
:(
```
         * schedule[Runs same command different schedule and same name.] action create[2017-06-02T20:15:42+00:00] INFO: Processing schedule[Runs same command different schedule and same name.] action create (some_test::default line 102)

           * windows_task[Runs same command different schedule and same name.] action create[2017-06-02T20:15:42+00:00] INFO: Processing windows_task[Runs same command different schedule and same name.] action create (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/some/resources/schedule.rb line 41)
       [2017-06-02T20:15:42+00:00] INFO: windows_task[Runs same command different schedule and same name.] task created



         * schedule[Runs same command different schedule and same name.] action create[2017-06-02T20:15:42+00:00] INFO: Processing schedule[Runs same command different schedule and same name.] action create (some::default line 106)

           * windows_task[Runs same command different schedule and same name.] action create[2017-06-02T20:15:42+00:00] INFO: Processing windows_task[Runs same command different schedule and same name.] action create (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/some/resources/schedule.rb line 41)
       [2017-06-02T20:15:42+00:00] INFO: windows_task[Runs same command different schedule and same name.] task already exists - nothing to do
        (up to date)
            (up to date)
```

**Comment by rosario-mattera** [comment]
Hi,
so which is the patch to be applied in order to get the interval update?

Regards

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
