### ISSUE TITLE
There is no enable_windows_task matcher for ChefSpec tests

### ISSUE THREAD

**Issue by ancoope** [chef-cookbooks/windows#367]
### Cookbook version
1.42.0

### Chef-client version
N/A

### Platform Details
Windows (all versions)

### Scenario:
Writing ChefSpec tests for a cookbook that disables and enables scheduled tasks.  There is no enable_windows_task matcher for the tests to use.

### Steps to Reproduce:
Create a recipe with the following resource:

```
windows_task 'Foo' do
  action :enable
end
```

Write a ChefSpec test for this recipe which include the test:
```
it 'should enable task Foo' do
  expect(chef_run).to enable_windows_task('Foo')
end
```

### Expected Result:
The test example should pass

### Actual Result:
An error occurs stating:

  NoMethodError:
    undefined method `enable_windows_task' ...

**Comment by tas50** [comment]
This has been shipped
