### ISSUE TITLE
Allow windows_feature to have definable timeout

### ISSUE THREAD

**Issue by jakauppila** [chef-cookbooks/windows#370]
### Cookbook version

1.41.0
### Chef-client version

12.2.1 (Latest version available for Windows on AWS OpsWorks)
### Platform Details

Server 2012 R2
### Scenario:

We specify an alternate source for WIM files that is not as close to the server as desired, so when installing a feature that contains many (like Web-Net-Ext) the installation takes longer than what appears to be a default 10 minute timeout. I would like to be able to define a timeout value.
### Steps to Reproduce:

You could define a source that's on a slow connection. We set the source via Registry with server creation.
### Expected Result:

Feature installs successfully after defined timeout
### Actual Result:

https://gist.github.com/Jakauppila/09f1dd243aac00ba86d7e33a8c4bfbde

**Comment by Tech356** [comment]
I also have this issue. I am attempting to enable a feature and the command is timing out after the default 600 seconds.

**Comment by DamonStamper** [comment]
I am also experiencing this behavior.

**Comment by jugatsu** [comment]
Also hit 600 sec timeout when installing .Net 3.5 on Windows Server 2016 in TK.

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.
