### ISSUE TITLE
Registry.key_exists? returns incorrect value when chef runs as native bitness

### ISSUE THREAD

**Issue by minadyn** [chef-cookbooks/windows#371]
### Cookbook version

1.41.0
### Chef-client version

12.11.18
### Platform Details

Microsoft Windows Server 2012 R2 Standard
Windows NT 6.2 AMD64
ruby 2.1.8p440 (2015-12-16 revision 53160) [x64-mingw32]
### Scenario:

I am trying to check for a registry key using Registry.key_exists? for a key that exists, but the function cannot find the key
### Steps to Reproduce:

To reproduce the problem, create a registry key, and check if it exists using Registry.key_exists?
This [gist](https://gist.github.com/minadyn/6f25f0d4bc9625cb41a322468f6faaa3) contains a simple recipe that does this.
### Expected Result:

Output should include 'registry key exists'
### Actual Result:

Output contains 'registry key does not exist' when running this [recipe](https://gist.github.com/minadyn/6f25f0d4bc9625cb41a322468f6faaa3)

[gist containing output](https://gist.github.com/minadyn/f508b426f90d992e0d4fe4c977128834)

I looked at the [registry_helper.rb](https://github.com/chef-cookbooks/windows/blob/v1.41.0/libraries/registry_helper.rb#L32) file and saw that, in my case, the PROCESSOR_ARCHITEW6432 variable was undefined and thus giving me 0x0200 as the value for the @@native_registry_constant variable.  

I did some searching and found that the 0x0200 value is used for accessing the 32 bit key ([source](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384129%28v=vs.85%29.aspx)), which in my case does not exist.  I'm running a 64 bit ruby process on a 64 bit OS, and according to [this](https://blogs.msdn.microsoft.com/david.wang/2006/03/27/howto-detect-process-bitness/) the PROCESSOR_ARCHITEW6432 variable will be undefined.

I think this can be fixed by checking if PROCESSOR_ARCHITEW6432 is undefined, and if so, check the PROCESSOR_ARCHITECTURE variable.  This will cover the case where chef runs as native bitness and return the proper processor architecture, rather than defaulting to accessing the 32 bit key.

**Comment by mwrock** [comment]
I'm curious if you see the same behavior using the registry DSL methods in core chef: https://docs.chef.io/dsl_recipe.html#registry-key-exists. Looking at that code which relies on ohai data and looking at how ohai gathers the data, I think it would use `0x0100` on 64bit chef. So we may want the helper in this cookbook to simply forward to the core helpers if it sees them and also deprecate them.

**Comment by minadyn** [comment]
I get the correct behavior on 64bit chef using the registry DSL methods.
