### ISSUE TITLE
windows_feature install fails with 'comparison of String with 6.2 failed'

### ISSUE THREAD

**Issue by camalot** [chef-cookbooks/windows#374]
### Cookbook version
1.44.0

### Chef-client version
12.11.18-1-x64

### Platform Details
Windows 2012r2

### Scenario:
Install a windows feature

### Steps to Reproduce:
Using the windows_feature_powershell provider, install a windows feature. It seems the commit [06c4a0e721711faf1c8fb3d7b9c88ebf99e35e11](https://github.com/chef-cookbooks/windows/commit/06c4a0e721711faf1c8fb3d7b9c88ebf99e35e11) is trying to compare the _os_version_ (string) to _6.2_ (number) is failing. 

### Expected Result:
Successfully install the windows feature

### Actual Result:
```
Error executing action `install` on resource 'windows_feature[AS-Incoming-Trans]'

ArgumentError
-------------
comparison of String with 6.2 failed
```

**Comment by anuriq** [comment]
fixed in https://github.com/chef-cookbooks/windows/pull/375

**Comment by tas50** [comment]
I'll have this fixed pushed to the Supermarket today.  Thanks for the report.
