### ISSUE TITLE
Compilation error with 2.0.0 due to Chef::Mixin::PowershellOut

### ISSUE THREAD

**Issue by yoshiwaan** [chef-cookbooks/windows#394]
### Cookbook version
2.0.0

### Chef-client version
12.X

### Platform Details
Ubuntu 14.04

### Scenario:
Chef run fails due to a compilation error

### Steps to Reproduce:
Just include the cookbook

### Expected Result:
Chef run fails

### Actual Result:
```
/root/.chef/local-mode-cache/cache/cookbooks/windows/providers/certificate_binding.rb:26:in `class_from_file'

Relevant File Content:
----------------------
/root/.chef/local-mode-cache/cache/cookbooks/windows/providers/certificate_binding.rb:
 19:  #
 20:
 21:  use_inline_resources
 22:
 23:  # See https://msdn.microsoft.com/en-us/library/windows/desktop/cc307236%28v=vs.85%29.aspx for netsh info
 24:
 25:  include Chef::Mixin::ShellOut
 26>> include Chef::Mixin::PowershellOut
 27:  include Windows::Helper
```

The mixin described no longer exists in the cookbook, but it's still required in a couple of places.

**Comment by tas50** [comment]
This has been fixed by adding back the powershell_out library to the cookbook. That being said I'd highly recommend upgrading Chef to a release post 12.6.0. Besides hundreds of other fixes that have been included you'll get an improved powershell_out mixin, and a greatly improved package resource.

**Comment by yoshiwaan** [comment]
:+1:
