### ISSUE TITLE
How to run chef-client on windows servers remotely. 

### ISSUE THREAD

**Issue by ranraq** [chef-cookbooks/windows#397]
### Cookbook version
12

### Chef-client version
12

### Platform Details
Windows 2012 R2

### Scenario:
Running chef-client on multiple windows servers 

### Issue
I have to install software on multiple windows 2012 servers. is there any way execute chef-client -o cookbook commands remotely? otherwise i have to login each server and run the command

**Comment by mwrock** [comment]
yes. Use [knife-windows](https://github.com/chef/knife-windows) and specifically the `knife winrm` command.
