### ISSUE TITLE
Issue with certificate binding

### ISSUE THREAD

**Issue by Chandra-Allaka** [chef-cookbooks/windows#404]
### Cookbook version
2.0.2

### Chef-client version
12.16.42

### Platform Details
Windows 2012 R2

### Scenario:
Trying to bind a ssl certificate to a site

### Steps to Reproduce:
Using the windows_certificate_binding resource

windows_certificate_binding node['iis_config']['sitename'] do
    cert_name 'IISSitecer'
    name_kind :hash
    port 443
    action :create
end

### Expected Result:
Proper certificate binding to the site. 

### Actual Result:
Error:  
RuntimeError
------------
A Cert with hash of IISSitecer doesn't exist in keystore LocalMachine\MY

I checked the provider certificate_binding.rb file. I figured out that the powershell script you are running is like below:
Test-Path "cert:\LocalMachine\MY\iissitecer"
This will always gives a 'false' output. 
I think it should instead be using the hash of the iissitecer as below
Test-Path "cert:\LocalMachine\MY\2a923a57ed2d54c711c9dca15541524b8326f504". This gives 'True' as output and then a successful output.
Please check.

**Comment by Chandra-Allaka** [comment]
Sorry, just checked in the help that the certificate name expected is the hash value itself and not the actual name. But I need to execute another powershell script to get that info. Can this be part of the resource itself?

**Comment by smurawski** [comment]
@Chandra-Allaka You can specify either the hash or the subject name of the certificate.  If you specify the `name_kind :subject` (or don't include `name_kind` as `:subject` is the default), you can use the subject name of the cert rather than the hash.
