### ISSUE TITLE
windows_task cookbook shows error that No resource or method named `windows_task' for `Chef::Recipe

### ISSUE THREAD

**Issue by ranraq** [chef-cookbooks/windows#406]
### Cookbook version
Chef 12.1

### Chef-client version
Chef 12.5

### Platform Details
Windows 2012 R2

### Scenario:
I am trying to create schedule task on Windows server 2012 R2 by using below recipe code. When i try to run cookbook on server, it shows error that No resource or method named `windows_task' for `Chef::Recipe "taskscheduler"'

 windows_task "WiresharkCapture" do
  user '****'
  password '****'
  cwd 'D:\\Temp'
  command 'D:\\SupportTools\\dumpcap_scheduler.bat'
  run_level :highest
  action :disable
 end
 
as per chef documentation windows_task is the resource name schedule task but still it shows error. 

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by mwrock** [comment]
This sounds to me like chef is not loading the windows cookbook in which case there would be no `windows_task` resource. Are you declaring a dependency on the windows cookbook in your metadata.rb?

**Comment by ranraq** [comment]
below is the code in my cookbook metadata.rb..  also i was able to use other windows resources like windows_package, powershell_script ec and able to execute recipes successfully.  only windows_task shows No resource or method named windows_task' forChef::Recipe 

name 'dbserverreadines'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dbserverreadines'
long_description 'Installs/Configures dbserverreadines'
version '0.1.0'

**Comment by mwrock** [comment]
`windows_package` and `powershell_script` are both defined in core chef. Based on your metadata you are not using this cookbook. You want to add `depends 'windows'` to your metdata.rb file and ensure that the windows cookbook is present on the node.

**Comment by ranraq** [comment]
i have updated depends 'windows' in my cookbook metadata.rb file and as below. 

name 'dbserverreadines'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dbserverreadines'
long_description 'Installs/Configures dbserverreadines'
version '0.1.0'
depends 'windows'

now when i try to execute recipe in my windows server, i am getting below error. Please help on this



  - dbserverreadines (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================

Recipe Compile Error in c:/chef/cache/cookbooks/windows/libraries/windows_privil
eged.rb
================================================================================


LoadError
---------
cannot load such file -- windows/error

Cookbook Trace:
---------------
  c:/chef/cache/cookbooks/windows/libraries/windows_privileged.rb:24:in `<top (r
equired)>'

Relevant File Content:
----------------------
c:/chef/cache/cookbooks/windows/libraries/windows_privileged.rb:

 17:  # distributed under the License is distributed on an "AS IS" BASIS,
 18:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 19:  # See the License for the specific language governing permissions and
 20:  # limitations under the License.
 21:  #
 22:
 23:  if RUBY_PLATFORM =~ /mswin|mingw32|windows/
 24>>   require 'windows/error'
 25:    require 'windows/registry'
 26:    require 'windows/process'
 27:    require 'windows/security'
 28:  end
 29:
 30:  #helpers for Windows API calls that require privilege adjustments
 31:  class Chef
 32:    class WindowsPrivileged
 33:      if RUBY_PLATFORM =~ /mswin|mingw32|windows/

Platform:
---------
x64-mingw32


Running handlers:
[2016-11-21T13:13:38+11:00] ERROR: Running exception handlers
Running handlers complete
[2016-11-21T13:13:38+11:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 07 seconds
[2016-11-21T13:13:38+11:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stack
trace.out
[2016-11-21T13:13:38+11:00] FATAL: Please provide the contents of the stacktrace
.out file if you file a bug report
[2016-11-21T13:13:38+11:00] FATAL: LoadError: cannot load such file -- windows/e
rror
