### ISSUE TITLE
release 2.1.0 breaks chef 11.X compatibility

### ISSUE THREAD

**Issue by arussellsaw** [chef-cookbooks/windows#410]
### Cookbook version
2.1.0
### Chef-client version
11.X

### Scenario:
recipes fail to compile on 11.X due to compat_resource checks in the required ohai version

### Steps to Reproduce:
run recipes depending on this cookbook with chef 11.X

### Expected Result:
issue a major release, or revert breaking changes

**Comment by tas50** [comment]
On 2016-09-07 I released the 2.0 version of this cookbook. That version removed support for Chef 11. This latest 2.1 release is utilizing more Chef 12 functionality that will probably hard break support for Chef 11. The support had already been removed in a major released though with a very large warning in the changelog and a post to the discourse mailing list. Chef 12 has been out for just about two years at this point. All of our community cookbooks support 12.1 or later so if you're still on 11 you're either going to have to stop upgrading cookbooks or upgrade the client.
