### ISSUE TITLE
WIN32OLERuntimeErrors on nano server

### ISSUE THREAD

**Issue by Happycoil** [chef-cookbooks/windows#419]
Originally posted in [chef-client](https://github.com/chef-cookbooks/chef-client/issues/439), I was asked to reopen it here.
### Cookbook version
2.1.1
7.0.0 (chef-client)

### Chef-client version
[12.14.60](https://s3-us-west-2.amazonaws.com/nano-chef-client/chef-12.14.60.appx)

### Platform Details
Windows Nano Server 10.0.14393.0

### Scenario:
if chef-client::task (or any other recipe which uses [wmi_property_from_query](https://github.com/chef-cookbooks/chef-client/blob/master/libraries/helpers.rb#L25)) is run on nano server it fails with a WIN32OLERuntimeError.

_Update from original issue:
While this cookbook doesn't contain that specific helper function, the offending `WIN32OLE.connect` line can be found [here](https://github.com/chef-cookbooks/windows/blob/09feee6f0a3a23060411ca70e3ec4ebea62f4241/libraries/wmi_helper.rb#L23), for instance._
### Steps to Reproduce:
Include chef-server::task in the run list of a nano server and converge

### Expected Result:
A scheduled task for chef-client is created

### Actual Result:
```
WIN32OLERuntimeError
--------------------
failed to parse display name of moniker `winmgmts://'
    HRESULT error code:0x80004005
      Unspecified error
```

As far as I can tell the line which throws the failure is [this one](https://github.com/chef-cookbooks/chef-client/blob/master/libraries/helpers.rb#L46), but any invocation of wmi_property_from_query will barf.

The relevant Win32_* classes are still queryable with CimCmdlets, for instance:
```powershell
[127.0.0.1]: PS C:\> Get-CimInstance -Query "select * from Win32_UserAccount where sid like 'S-1-5-21-%-500' and LocalAccount=True"

Name             Caption                                  AccountType                              SID                                      Domain
----             -------                                  -----------                              ---                                      ------
Administrator    Nano\Administrator                       512                                      S-1-5-21-850424881-462263701-29929842... Nano
```

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
