### ISSUE TITLE
windows_package: check that package is installed before reporting success

### ISSUE THREAD

**Issue by yetanotherion** [chef-cookbooks/windows#422]
### Cookbook version
1.44.1

### Chef-client version
12.8.1

### Platform Details
Windows Server 2012R2

### Scenario:
Converging a buggy windows_package recipe that has a bad package name.

### Steps to Reproduce:
Add a recipe:

```
windows_package 'Not the package name' do
  source 'https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.1/Git-2.11.0-64-bit.exe'
  checksum 'fd1937ea8468461d35d9cabfcdd2daa3a74509dc9213c43c2b9615e8f0b85086'
end
```

The package is installed and reinstalled at each run of chef-client as the name of the package is
'Git version 2.11.0' (!= 'Not the package name')

### Expected Result:
Chef does not converge

### Actual Result:
Chef converges but reinstalls the package at each run of chef-client.

The idea would consist at computing another variable than status
https://github.com/chef-cookbooks/windows/blob/fcd5d37f9959498e6d7647210235928d911c1b1d/libraries/windows_package.rb#L35
to verify that @new_resource.package_name is in the
new list of installed_packages
https://github.com/chef-cookbooks/windows/blob/5f07cde489f044e028309da42faa8b2789443b22/libraries/windows_helper.rb#L110

**Comment by mwrock** [comment]
closing here since `windows_package` in this cookbook is deprecated and now handled from core chef.
