### ISSUE TITLE
Uprading cookbook from 2.1.1 -> 3.0.0 gives NoMethodError: undefined method `remote_file' for Custom resource windows_zipfile from cookbook windows when unzipping remote file

### ISSUE THREAD

**Issue by adybuxton** [chef-cookbooks/windows#446]
### Cookbook version
3.0.0

### Chef-client version
12.19.36

### Platform Details
Windows 10

### Scenario:
Upgrading the cookbook from 2.1.1 -> 3.0.0

### Steps to Reproduce:
Upgrading the cookbook from 2.1.1 -> 3.0.0

### Expected Result:
Remote zip files to download and unzip

### Actual Result:

[2017-03-16T13:55:52+00:00] FATAL: NoMethodError: windows_zipfile[C:/] (cookbook::test line 2) had an error: NoMethodError: undefined method `remote_file' for Custom resource windows_zipfile from cookbook windows

**Comment by kalapakim** [comment]
I have the same error...

**Comment by rjhornsby** [comment]
stacktrace:
```
Generated at 2017-03-17 14:08:57 -0700
NoMethodError: windows_zipfile[c:/tmp/] (<mycookbook>::<myrecipe> line 13) had an error: NoMethodError: undefined method `remote_file' for Custom resource windows_zipfile from cookbook windows
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource.rb:1364:in `method_missing'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/windows/libraries/windows_helper.rb:82:in `cached_file'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/windows/resources/zipfile.rb:36:in `block (2 levels) in class_from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/provider.rb:176:in `converge_by'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/windows/resources/zipfile.rb:35:in `block in class_from_file'
(eval):2:in `block in action_unzip'
...truncated
```

Complete contents of [stacktrace.out](https://gist.github.com/rjhornsby/9afe8aaa51f35f4e2fb89ca87f42b6a7) in gist

**Comment by lbn-chef-team** [comment]
idem

**Comment by pkleanthous** [comment]
Hi guys,

I'm facing the same issue. Do you have any updates?

**Comment by smurawski** [comment]
Fixed in the next release of this cookbook via #452

**Comment by pkleanthous** [comment]
@smurawski 

Nice one! Excellent work.
