### ISSUE TITLE
windows_share: Win32_Share.create returned 1 on Windows 7SP1, POSREADY 7 (6.1.7601)

### ISSUE THREAD

**Issue by jugatsu** [chef-cookbooks/windows#448]
### Cookbook version
3.0

### Chef-client version
12.19.36

### Platform Details
Windows 7 SP1, Windows POSReady 7

### Scenario:
Create windows share with `windows_share` resource

### Steps to Reproduce:
```ruby
directory 'c:/test_share' do
  rights  :full_control, 'BUILTIN\\Users'
end

windows_share 'read_only' do
  path            'C:/test_share'
  description     'a test share'
  read_users      ['BUILTIN\\Users']
end
```
### Expected Result:
Windows share is created
### Actual Result:
Chef-client fails with `Win32_Share.create returned 1` error.

**Comment by jugatsu** [comment]
https://github.com/chef-cookbooks/windows/blob/master/resources/share.rb#L156
I just run
```powershell
      $share = [wmiclass]"\\\\#{ENV['COMPUTERNAME']}\\root\\CimV2:Win32_Share"
      $result=$share.Create('#{new_resource.path}',
                            '#{new_resource.share_name}',
                            0,
                            16777216,
                            '#{new_resource.description}',
                            $null,
                            $null)
      exit $result.returnValue

```
locally on host with Powershell 2.0. And windows share was created without any issues.

But converging with `windows_share` returns error.

**Comment by smurawski** [comment]
@jugatsu How are you running chef-client?  Scheduled task? Service? over WinRM?

**Comment by jugatsu** [comment]
In test-kitchen under vagrant user over WinRM.

**Comment by mwrock** [comment]
Over winrm, you will run into the double hop issue with shares. However you should be able to work around that by using the elevated winrm transport:
```
transport:
  name: winrm
  elevated: true
```

**Comment by jugatsu** [comment]
I _can_ converge with `elavated: true` and also `elevated: false`
But strange thing that i noticed that i get error `Win32_Share.create returned 1` after second run, it converged successfully on first chef-client run. On second - it fails
```ruby
 windows_share[Cash] action create
       
           ================================================================================
           Error executing action `create` on resource 'windows_share[Cash]'
           ================================================================================
       
           RuntimeError
           ------------
           Could not create share.  Win32_Share.create returned 1
       

```
@mwrock any advice how i can debug further.

**Comment by smurawski** [comment]
@jugatsu was that a second converge with `elevated: true` or one with `elevated: true` and one not?

Also, I just created a PR to deal with #447, so I'd appreciate if you could test against that after it is merged.

I don't have that particular sku of Windows to test against, but I did test it against Server 2008 R2 SP1 and it works properly there.

**Comment by jugatsu** [comment]
@smurawski second converge was also with `elavated: true`

I will test against master after it is merged :+1:

**Comment by jugatsu** [comment]
Can't reproduce anymore with v3.0.1. I think this was a bug in my cookbook, not `windows` cookbook.

**Comment by prsshini** [comment]
I get the same error. how did u guys resolve this? i am stuck with this for a long time..and I am trying to  use pwershell tocreate share.. but I am curious in resolving this to work for me..
metadata.rb
depends 'windows', '~> 3.1.2'

recipe.rb

windows_share 'share' do
  action :create
  path 'C:\\share"
  read_users ['Prod\\abdeef']
end


                                                                                                                                                                                                                     ================================================================================                                                                                                                           Error executing action `create` on resource 'windows_share[share]'                                                                                                                                     ================================================================================                                                                                                                                                                                                                                                                                                                                      RuntimeError                                                                                                                                                                                               ------------                                                                                                                                                                                               Could not create share.  Win32_Share.create returned 1                                                                                                                                                                                                                                                                                                                                                                Resource Declaration:                                                                                                                                                                                      ---------------------                                                                                                                                                                                      # In                                                                                                                                                                                                                                                                                                           20: windows_share "share" do                                                                                                                                                                           21:   action :create                                                                                                                                                                                       22:   path 'C:/share'                                                                                                                                                                                   23:   read_users ['Prod\\abdeef']                                                                                                                                                                          24: end                                                                                                                                                                                                                                                                                                                                                                                                              Compiled Resource:                                                                                                                                                                                         ------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                          windows_share("share") do                                                                                                                                                                                action [:create]                                                                                                                                                                                           retries 0                                                                                                                                                                                                  retry_delay 2                                                                                                                                                                                              default_guard_interpreter :default                                                                                                                                                                         declared_type :windows_share                                                                                                                                                                               cookbook_name "russell-chef-client"                                                                                                                                                                        recipe_name "default"                                                                                                                                                                                      path "C:/share"                                                                                                                                                                                         read_users ["Prod\\abdeef"]                                                                                                                                                                                share_name "share"                                                                                                                                                                                   end                                                                                                                                                                                                                                                                                                                                                                                                                   Platform:                                                                                                                                                                                                  ---------                                                                                                                                                                                                  x64-mingw32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Running handlers:                                                                                                                                                                                          [2017-09-13T10:20:51-07:00] ERROR: Running exception handlers                                                                                                                                              Running handlers complete                                                                                                                                                                                  [2017-09-13T10:20:51-07:00] ERROR: Exception handlers complete                                                                                                                                             Chef Client failed. 0 resources updated in 04 seconds                                                                                                                                                      [2017-09-13T10:20:51-07:00] FATAL: Stacktrace dumped to
                                                [2017-09-13T10:20:51-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report                                                                                         [2017-09-13T10:20:51-07:00] FATAL: RuntimeError: windows_share[share] (xxxx::default line 20) had an error: RuntimeError: Could not create share.  Win32_Share.create returned 1
