### ISSUE TITLE
Failure on windows_feature resource

### ISSUE THREAD

**Issue by emmanuelguerin** [chef-cookbooks/windows#454]
### Cookbook version
3.0.0

### Chef-client version
chef client 12.19

### Platform Details
Windows 2012R2 in Azure

### Scenario:
When using windows_feature resource, a failure can occur.

### Steps to Reproduce:
Use the following resource:

```
windows_feature 'NetFx3' do
  8:   action :install
  9:   all true
 10: end
```

### Expected Result:

On all runs, the resource should make sure that the feature is installed, without error.

### Actual Result:

After the feature was installed by the first chef-client run, the following ones fail with the following error.

```
NoMethodError
windows_feature_dism[NetFx3] (c:/chef/cache/cookbooks/windows/resources/feature.rb line 44) had an error: NoMethodError: undefined method `feature' for Custom resource windows_feature_dism from cookbook windows
Cookbook Trace:
c:/chef/cache/cookbooks/windows/resources/feature_dism.rb:77:in `block in class_from_file'
Resource Declaration:
# In c:/chef/cache/cookbooks/tssql/recipes/server2014.rb

  7: windows_feature 'NetFx3' do
  8:   action :install
  9:   all true
 10: end
```

**Comment by smurawski** [comment]
Fixed with #456.  Thanks for the report and the fix @emmanuelguerin
