### ISSUE TITLE
windows_task not idempotent on systems with codepage other than 437

### ISSUE THREAD

**Issue by jugatsu** [chef-cookbooks/windows#462]
### Cookbook version
3.0.4

### Chef-client version
12.19.36
### Platform Details
Windows Server 2012 R2 Russian Edition
Windows Hyper-V Server 2016 Russian Edition
### Steps to Reproduce:
converge recipe multiple times. task created on each chef-client run
```ruby
windows_task 'task_locale_ru' do
  command 'dir'
  user 'Пользователь'
  password 'SeaPower1@3'
  run_level :highest
  action :create
end
```
### Expected Result:
`windows_task` should report `up to date` after first converge

### Actual Result:
task created on each chef-client run

**Comment by smurawski** [comment]
@jugatsu Thanks for the issue and the PR!

**Comment by jugatsu** [comment]
Fixed in https://github.com/chef-cookbooks/windows/pull/463
