### ISSUE TITLE
7-zip dependancy depricated and not-working in chef 13

### ISSUE THREAD

**Issue by LuneraSteve** [chef-cookbooks/windows#467]
### Cookbook version
Current

### Chef-client version
13.0.118

### Platform Details
Windows is a dependency of Java cookbook which I'm using on Ubuntu 16.04

### Scenario:
I'm trying to converge a node that is really not related to anything going on in this cookbook.  The problem is that windows cookbook is a dependency of a dependency and one of windows dependencies isn't happy.  Fun stuff, eh?

### Steps to Reproduce:
Create a .kitchen.yml file to build an Ubuntu 16.04 node that has Java as a dependency and watch it break.

```
...
       Starting Chef Client, version 13.0.118
...
       Synchronizing Cookbooks:
         - java (1.48.0)
         - apt (2.9.2)
         - jenkins (5.0.0)
         - nginx (2.7.6)
         - windows (2.0.2)
         - homebrew (4.0.0)
         - runit (1.8.0)
         - compat_resource (12.19.0)
         - dpkg_autostart (0.2.0)
         - bluepill (2.4.3)
         - build-essential (2.4.0)
         - ohai (2.1.0)
         - yum-epel (0.7.1)
         - packagecloud (0.3.0)
         - rsyslog (6.0.1)
         - yum (5.0.1)
         - 7-zip (1.0.2)
...
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/7-zip/attributes/default.rb
       ================================================================================
       
       NoMethodError
       -------------
       undefined method `kernel' for #<Chef::Node::Attribute:0x00000003f0f250>
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/7-zip/attributes/default.rb:21:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/7-zip/attributes/default.rb:
       
        14:  # Unless required by applicable law or agreed to in writing, software
        15:  # distributed under the License is distributed on an "AS IS" BASIS,
        16:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        17:  # See the License for the specific language governing permissions and
        18:  # limitations under the License.
        19:  #
        20:  
        21>> if kernel['machine'] =~ /x86_64/
        22:    default['7-zip']['url']          = "http://downloads.sourceforge.net/sevenzip/7z922-x64.msi"
        23:    default['7-zip']['checksum']     = "f09bf515289eea45185a4cc673e3bbc18ce608c55b4cf96e77833435c9cdf3dc"
        24:    default['7-zip']['package_name'] = "7-Zip 9.22 (x64 edition)"
        25:  else
        26:    default['7-zip']['url']          = "http://downloads.sourceforge.net/sevenzip/7z922.msi"
        27:    default['7-zip']['checksum']     = "86df264d22c3dd3ab80cb55a118da2d41bdd95c2db2cd09a6bbdf48f069e3d7a"
        28:    default['7-zip']['package_name'] = "7-Zip 9.22"
        29:  end
        30:  
```
### Expected Result:
I'm expecting to get to the end of my converge without error.

### Actual Result:
See output above.

### Notes:

I realize this isn't really an issue you guys have created or maintain... but you should change the dependency from `7-zip` to `seven_zip`.  See here:  https://github.com/sneal/7-zip#deprecated

**Comment by smurawski** [comment]
@LuneraSteve The windows cookbook (v2.0.2 which you have listed and the current version) doesn't have a dependency on the 7-zip cookbook.  If you have the Berksfile.lock generated by test-kitchen, you should be able to see which cookbook actually has the deprecated dependency.

**Comment by LuneraSteve** [comment]
Looks like its nginx.  My Berksfile points a big finger at you guys right out of the gate.  Sorry about that.

**Comment by smurawski** [comment]
No worries @LuneraSteve.  Glad you found the right cookbook to apply the feedback to.

**Comment by Seb2nim** [comment]
@LuneraSteve : how did you solved that ?

**Comment by ernie58** [comment]
@LuneraSteve Having trouble with this also? How did you solve the issue in the Nginx cookbook?

**Comment by tas50** [comment]
There's no way around it if you're using the nginx cookbook as the author has not updated that cookbook in several years. We have a fork here at chef named chef_nginx that has been updated to work on modern distros and to not constrain dependencies like the windows cookbook. If you use that cookbook instead you'll avoid this problem.
