### ISSUE TITLE
windows_pagefile resource does not fail if it can't assign pagefile due to disk space

### ISSUE THREAD

**Issue by crocketttubbs** [chef-cookbooks/windows#469]
### Cookbook version
1.40.0

### Chef-client version
12.9.41

### Platform Details
Windows 2008 R2

### Scenario:
Chef client running the page file resource does not fail when there is not enough disk space to assign the page file.

Received this error, but chef-client run completed normally:

windows_pagefile[c:\pagefile.sys] action set[2017-05-08T11:13:16-04:00] FATA
L: ERROR:
Description = Value out of range

### Steps to Reproduce:
Attempt to create a page file larger than the disk will allow.

### Expected Result:
Chef client run should fail.

### Actual Result:
Chef client run does not fail.

**Comment by tas50** [comment]
I've reworked the failure logic in the 3.1.1 release so that it actually fails when one of the commands returns an error. It also includes more debug level logging if you're curious what it's actually trying to do.
