### ISSUE TITLE
windows_certificate_binding doesn't work with 'Default Web Site'

### ISSUE THREAD

**Issue by Chandra-Allaka** [chef-cookbooks/windows#474]
### Cookbook version
3.0.5

### Chef-client version
13.0.118

### Platform Details
Windows Server 2012 R2

### Scenario:
[I am trying to edit the bindings of the 'Default Web Site' on IIS and configure https with a certificate already present in MY store.

### Steps to Reproduce:
The resource in recipe is described as below:

windows_certificate_binding 'Default Web Site' do
 cert_name 'abcdef...' #cert thumbprint
 name_kind :hash
 port 443
action :create
end
### Expected Result:
I expect the 'Default Web Site' to have the https binding on port 443 with the certificate provided.

### Actual Result:
The cookbook completes successfully but the binding doesn't happen. Nothing changes in actuals.

**Comment by iennae** [comment]
Can you check version 3.1.0 of this cookbook to see if your issue is resolved?

**Comment by iennae** [comment]
If this is still a problem, please reopen with details. Thanks.
