### ISSUE TITLE
v2.1.1/recipes/default.rb#L24 is causing chef-client to fail.

### ISSUE THREAD

**Issue by suchakra** [chef-cookbooks/windows#477]
Issue RC, as well as temporary manual workaround is best explained in '[Steps to Reproduce](#Steps-to-Reproduce)' below. It appears to be because of how the win32-api gem has been defined. Earlier it used to work because [it was generic](https://github.com/cosmo0920/win32-api/blob/win32-api-1.4.8/Rakefile#L89). However [now](https://github.com/cosmo0920/win32-api/blob/win32-api-1.6.1.2/Rakefile#L166) they have started including non-standard platform hint.
Point is now you do not need to [send the option --platform](https://github.com/chef-cookbooks/windows/blob/v2.1.1/recipes/default.rb#L24) anymore.

### Cookbook version
2.1.1

### Chef-client version
12.19.36

### Platform Details
Windows Server 2012 R2 Standard

### Scenario:
run chef-client where my recipe says 'include_recipe "windows"'.

### Steps to Reproduce
```
PS C:\opscode\chef\embedded\bin> ./gem install win32-api -q --no-rdoc --no-ri -v "1.6.1.2" --platform=mswin32
ERROR:  Could not find a valid gem 'win32-api' (= 1.6.1.2) in any repository
ERROR:  Possible alternatives: win32-api
PS C:\opscode\chef\embedded\bin> ./gem install win32-api -q --no-rdoc --no-ri --platform=mswin32
Building native extensions.  This could take a while...
Successfully installed win32-api-1.4.8
1 gem installed
PS C:\opscode\chef\embedded\bin> ./gem install win32-api -q --no-rdoc --no-ri -v "1.6.1.2"
Successfully installed win32-api-1.6.1.2-universal-mingw32
1 gem installed
PS C:\opscode\chef\embedded\bin>
```

### Expected Result:
windows:default recipe runs successfully.

### Actual Result:
Generated at 2017-06-08 13:52:31 -0400
Mixlib::ShellOut::ShellCommandFailed: chef_gem[win32-api] (windows::default line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of c:/opscode/chef/embedded/bin/gem install win32-api -q --no-rdoc --no-ri -v "1.6.1.2" --platform=mswin32 ----
STDOUT: 
STDERR: ERROR:  Could not find a valid gem 'win32-api' (= 1.6.1.2) in any repository
ERROR:  Possible alternatives: win32-api
---- End output of c:/opscode/chef/embedded/bin/gem install win32-api -q --no-rdoc --no-ri -v "1.6.1.2" --platform=mswin32 ----
Ran c:/opscode/chef/embedded/bin/gem install win32-api -q --no-rdoc --no-ri -v "1.6.1.2" --platform=mswin32 returned 2
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout.rb:289:in `invalid!'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout.rb:276:in `error!'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/shell_out.rb:118:in `shell_out!'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:637:in `shell_out_with_timeout!'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package/rubygems.rb:546:in `install_via_gem_command'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package/rubygems.rb:527:in `install_package'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:114:in `block (3 levels) in <class:Package>'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:272:in `multipackage_api_adapter'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:113:in `block (2 levels) in <class:Package>'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider.rb:176:in `converge_by'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:112:in `block in <class:Package>'
(eval):2:in `block in action_install'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_install'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:97:in `each'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:96:in `converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:665:in `catch'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:665:in `converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:284:in `run'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:59:in `run'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/bin/chef-client:26:in `<top (required)>'
c:/opscode/chef/bin/chef-client:68:in `load'
c:/opscode/chef/bin/chef-client:68:in `<main>'

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of c:/opscode/chef/embedded/bin/gem install win32-api -q --no-rdoc --no-ri -v "1.6.1.2" --platform=mswin32 ----
STDOUT: 
STDERR: ERROR:  Could not find a valid gem 'win32-api' (= 1.6.1.2) in any repository
ERROR:  Possible alternatives: win32-api
---- End output of c:/opscode/chef/embedded/bin/gem install win32-api -q --no-rdoc --no-ri -v "1.6.1.2" --platform=mswin32 ----
Ran c:/opscode/chef/embedded/bin/gem install win32-api -q --no-rdoc --no-ri -v "1.6.1.2" --platform=mswin32 returned 2
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout.rb:289:in `invalid!'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout.rb:276:in `error!'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/shell_out.rb:118:in `shell_out!'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:637:in `shell_out_with_timeout!'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package/rubygems.rb:546:in `install_via_gem_command'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package/rubygems.rb:527:in `install_package'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:114:in `block (3 levels) in <class:Package>'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:272:in `multipackage_api_adapter'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:113:in `block (2 levels) in <class:Package>'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider.rb:176:in `converge_by'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider/package.rb:112:in `block in <class:Package>'
(eval):2:in `block in action_install'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_install'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:97:in `each'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:96:in `converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:665:in `catch'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:665:in `converge'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:284:in `run'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:59:in `run'
c:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/bin/chef-client:26:in `<top (required)>'
c:/opscode/chef/bin/chef-client:68:in `load'
c:/opscode/chef/bin/chef-client:68:in `<main>'

**Comment by tas50** [comment]
The default recipe shouldn't be necessary with Chef 12.19. Also with 12.19 you can run Windows cookbook 3+ which entirely removes the failing code you're running into.

https://github.com/chef-cookbooks/windows/blob/master/recipes/default.rb
