### ISSUE TITLE
windows_task resource changes powershell output encoding which interferes with later recipes

### ISSUE THREAD

**Issue by FreakyDug** [chef-cookbooks/windows#478]
### Cookbook version
3.1.1

### Chef-client version
12.9.41

### Platform Details
Windows 7

### Scenario:
When the windows task resource checks to see if the task already exists, it uses a powershell command which changes the Output Encoding to UTF8:

https://github.com/chef-cookbooks/windows/blob/master/resources/task.rb#L62

This is causing the chocolate_package resource in subsequent recipes to fail with the following error:

> Chef::Exceptions::MissingLibrary: Could not locate your Chocolatey install. To install chocolatey, we recommend the 'chocolatey' cookbook (https://github.com/chocolatey/chocolatey-cookbook). If Chocolatey is installed, ensure that the 'ChocolateyInstall' environment variable is correctly set. You can verify this with the PowerShell command '[System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'MACHINE')'.

If you run the suggested powershell command ChocolateyInstall looks fine, but the value ruby gets when it runs that command via powershell_out begins with junk:

![image](https://user-images.githubusercontent.com/2656101/27326609-d22f7448-55a3-11e7-84ef-c4d189e9bd61.png)

Via the interactive ruby interpreter, I can see those junk characaters are actually the unicode BOM:

> <ronment]::GetEnvironmentVariable('ChocolateyInstall', 'MACHINE')").stdout
> => "\xEF\xBB\xBFC:\\ProgramData\\chocolatey\r\n"

For some reason, I am only experiencing this problem on machines with the en-us locale (which all happen to be Windows 7), my hosts in the UK are fine (including Windows 7 machines).

### Steps to Reproduce:
Put a recipe with a chocolatey_package resource in it after a recipe with a windows_task resource in it.

**Comment by jugatsu** [comment]
I was having similar issues with chocolatey and test-kitchen. See comment https://github.com/WinRb/winrm-elevated/pull/18

Actually I'm the author of https://github.com/chef-cookbooks/windows/pull/463 :) which introduces UTF encoding.

Can you reproduce with chef 12? I don't have any issues with converging node with `chocolatey_package` and `windows_tasks` in `run_list`.

**Comment by FreakyDug** [comment]
Do you mean chef 13? I've only seen it with 12(.9.41). I'm currently upgrading my nodes to 13, so I can try it once that's done.

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
