### ISSUE TITLE
any update for Windows 2016?

### ISSUE THREAD

**Issue by aidda** [chef-cookbooks/windows#484]
This cookbook doesnt suppoty Windows Server 2016.
so when I want to add a new feauter to Server Manager to install .Net 3.5, I got this error:
```
    amazon-ebs: Ran C:\Windows\system32\dism.exe /online /enable-feature /featurename:NetFx3 /norestart  /All returned 5
    amazon-ebs:
    amazon-ebs: Resource Declaration:
    amazon-ebs: ---------------------
    amazon-ebs: # In c:/windows/temp/local-mode-cache/cache/cookbooks/windows/resources/feature.rb
    amazon-ebs:
    amazon-ebs: 60:       windows_feature_dism new_resource.name do
    amazon-ebs: 61:         action desired_action
    amazon-ebs: 62:         feature_name new_resource.feature_name
    amazon-ebs: 63:         source new_resource.source if new_resource.source
    amazon-ebs: 64:         all new_resource.all
    amazon-ebs: 65:       end
    amazon-ebs: 66:     when :windows_feature_servermanagercmd
    amazon-ebs:
    amazon-ebs: Compiled Resource:
    amazon-ebs: ------------------
    amazon-ebs: # Declared in c:/windows/temp/local-mode-cache/cache/cookbooks/windows/resources/feature.rb:60:in `run_default_provider'
    amazon-ebs:
    amazon-ebs: windows_feature_dism("NetFx3") do
    amazon-ebs: action [:install]
    amazon-ebs: updated true
    amazon-ebs: updated_by_last_action true
    amazon-ebs: default_guard_interpreter :default
    amazon-ebs: declared_type :windows_feature_dism
    amazon-ebs: cookbook_name "ff_dotnet"
    amazon-ebs: feature_name "NetFx3"
    amazon-ebs: all true
    amazon-ebs: end
    amazon-ebs:
    amazon-ebs: System Info:
    amazon-ebs: ------------
    amazon-ebs: chef_version=13.2.20
    amazon-ebs: platform=windows
    amazon-ebs: platform_version=10.0.14393
    amazon-ebs: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
    amazon-ebs: program_name=c:/opscode/chef/bin/chef-solo
    amazon-ebs: executable=c:/opscode/chef/bin/chef-solo
    amazon-ebs:
    amazon-ebs:
    amazon-ebs: ================================================================================
    amazon-ebs: Error executing action `install` on resource 'windows_feature[NetFx3]'
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: Mixlib::ShellOut::ShellCommandFailed
    amazon-ebs: ------------------------------------
    amazon-ebs: windows_feature_dism[NetFx3] (c:/windows/temp/local-mode-cache/cache/cookbooks/windows/resources/feature.rb line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 42, 127, 3010], but received '5'
```
It needs to run `dism /online /enable-feature /featurename:NetFx3ServerFeatures /Source:D:\sources\sxs , before.
`

**Comment by mwrock** [comment]
Are you running the chef client as an administrator in an elevated console?

Exit code 5 is an access denied error and usually indicates insufficient privileges.

**Comment by aidda** [comment]
@mwrock I'm using Packer to build windows server 2016 ami from ec2 builder. 
Cookbook by itself works well, but when i tried to run it with chef solo in packer it doesn't work. On the other hand, i can execute command for enabling netfx3 feature from packer, but the same command doesn't work with powershell_script resource from recipe.
Any suggestions?

**Comment by mwrock** [comment]
Ah ok. Yes this is an unfortunate shortcoming of the packer chef solo provisioner. It does not run with elevated privileges. You will need to run these commands separately in the powershell packer provisioner. I'll close this issue since this is a packer issue.

**Comment by aidda** [comment]
@mwrock Whould you please explain to me why this behavior apper through the packer? I ask my question in Packer commiunity and I`m waiting for answer from them ..

**Comment by mwrock** [comment]
The packer chef solo provisioner simply runs chef client via a winrm remote session. Certain tasks such as installing some windows features or updates will always fail in a remote session. The common way to work around that is to use a scheduled task via the remote session. Your remote session creates and runs the scheduled task and the task executes in a local security context. The chef solo provisioner does not employ that work around. However the powershell porvisioner does as long as you provide credentials.
