### ISSUE TITLE
find_provider_for_node deprecation warnings

### ISSUE THREAD

**Issue by sspans** [chef-cookbooks/windows#487]
### Cookbook version
3.1.1 - Latest released version

### Chef-client version
12.21.3

### Platform Details
Centos 7

### Scenario:
Clean chef-client run

### Steps to Reproduce:
Run chef-client

### Expected Result:
No deprecation warnings from chef-client

### Actual Result:

```
  Chef::Platform.find_provider_for_node is deprecated at 1 location:
    - /opt/chef/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
   See https://docs.chef.io/deprecations_chef_platform_methods.html for further details.
  Chef::Platform.find_provider is deprecated at 1 location:
    - /opt/chef/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
   See https://docs.chef.io/deprecations_chef_platform_methods.html for further details.
  Chef::Platform.find is deprecated at 1 location:
    - /opt/chef/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
   See https://docs.chef.io/deprecations_chef_platform_methods.html for further details.
```

Triggered by https://github.com/chef-cookbooks/windows/blob/master/libraries/windows_helper.rb#L55

**Comment by tas50** [comment]
This has been resolved in the newest releases. Try out the new version and feel free to open this back up if you're still seeing it.
