### ISSUE TITLE
DISM & Powershell windows_feature install_method have opposite "all" feature

### ISSUE THREAD

**Issue by Annih** [chef-cookbooks/windows#493]
### Cookbook version
Version **>= 3**

### Scenario:
DISM & PowerShell windows_feature install method doesn't have equivalent `all` feature.
The following resources are clearly not equivalent and can lead to buggy behavior like criteo-cookbooks/wsus-server#26

```
windows_feature 'UpdateServices' do
  install_method :windows_feature_dism
  all      true
end
```
According to the DISM help this will enable the `UpdateServices` feature and all its parents
> Use /All to enable all parent features of the specified feature

Whereas below feature will enable the `UpdateServices` feature and all its children
```
windows_feature 'UpdateServices' do
  install_method :windows_feature_powershell
  all true
end
```

### Expected Result:
I would expect to have both resource doing the same thing :D

### Actual Result:
With DISM it works properly, with PowerShell it fails (see criteo-cookbooks/wsus-server#26)

Regards.

*Cc.* @aboten

**Comment by iennae** [comment]
@stuartpreston Can you take a look at this when you get a chance? Thanks!

**Comment by stuartpreston** [comment]
@Annih I had a look into this and verified the behavior you are seeing.

- In version =2.1.1 of the windows cookbook we did not have the option to specify the `-IncludeAllSubFeatures` when using the PowerShell provider and the `all` property was set to true on the resource.  
- In version >=3 of the windows cookbook we add `-IncludeAllSubFeatures` which installs ["all subfeatures of parent roles, role services, or features specified"](https://technet.microsoft.com/en-us/itpro/powershell/windows/servermanager/install-windowsfeature) if the `all` property is set to true on the resource.  

So it's not quite _opposite_ behaviour - a completely different of features can be selected depending on the provider used, especially as the PowerShell install method selects all dependencies (parent items) by default.  Additionally, as you are no doubt aware - the feature names can differ between DISM and PowerShell too.

The [documentation](https://github.com/chef-cookbooks/windows#windows_feature) will be updated to highlight this difference in behavior across the install methods.  As you have discovered, you will need to explicitly set `install_method` if you wish to use the PowerShell Install-WindowsFeature method.  Setting the `all` property should not be required in this case.

**Comment by Annih** [comment]
Hello @stuartpreston 
I'm OK with an update of the documentation , it would at least help people decide when to use `all` or not.
Thanks for the feedback, I'll findout which solution I want to apply for my bug :)
