### ISSUE TITLE
windows_task lacks a description property

### ISSUE THREAD

**Issue by mcfisch** [chef-cookbooks/windows#497]
### Cookbook version
3.1.2

### Chef-client version
12.18.31
### Platform Details
Windows 2008+

### Scenario:
Creating a scheduled task in Windows with a description to appear in the management console.

### Steps to Reproduce:
```
windows_task 'restart_lucene_services' do
  run_level :highest
  command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy RemoteSigned -file \'CUSTOM_SCRIPT_PATH\''
  description 'Runs a PowerShell script every 15 minutes to automatically restart service XYZ if conditions are met'
  user 'SYSTEM'
  frequency :minute
  frequency_modifier 15
  action [:create, :enable]
end
```

### Expected Result:
Scheduled task in Windows being created, having a description as specified.

### Actual Result:
Chef-client fails due to non-existent property `description` in resource `windows_task`.

### Feature Request:
Please add a `description` property for the `windows_tasks` resource. This allows to give other users an idea what a task actually is for, since not every user is involved in the automated setup.

**Comment by tas50** [comment]
The windows_task resource was integrated into Chef 13 and development on this resource has ended as we've made a large number of improvements to the resource within chef itself. I encourage you to try the resource in the latest Chef release and file a bug against the chef repo itself if this is still an issue.
