### ISSUE TITLE
Appeveyor is not passing

### ISSUE THREAD

**Issue by jakauppila** [chef-cookbooks/windows#498]
Just wanted to open up an issue on the fact that Appveyor is currently not passing on master. I've been planning on tackling a number of open issues, but haven't had a reliable way to test.

It appears to be a WinRM bug? Not sure who needs to be involved.

**Comment by jakauppila** [comment]
@tas50 Any thoughts on this?

**Comment by iennae** [comment]
We need to fix it. I fixed the cookstyle issues but there is still an issue with this PR https://github.com/chef-cookbooks/windows/pull/499 introduced a bug that is causing the failure.

**Comment by tas50** [comment]
There's a few more failures we need to work out. I'm looking into it

**Comment by tas50** [comment]
I've cut a few more things over to InSpec which is part of the fix, but there's still a few to go.

**Comment by tas50** [comment]
We're now just failing on windows_share stuff, which is known broken. Once that gets resolved we'll be back to green here.

**Comment by tas50** [comment]
PASSING!
