### ISSUE TITLE
Deprecated features used! warning when ysubg windows_zipfile resource

### ISSUE THREAD

**Issue by ldliy1** [chef-cookbooks/windows#507]
### Cookbook version
3.1.3

### Chef-client version
13.5.3

### Platform Details
Windows server 2012R2 v6.3 Build 9600

### Scenario:
windows_zipfile 'C:\folder\path' do
  source 'https://linklocation.com/file.zip'
  action :unzip
  not_if {::Dir.exist?('c:\folder')}
end

### Steps to Reproduce:
Try unzip file as per above

### Expected Result:
Expected result is to unzip content, which it does... however, I get an `Deprecated features used!` notice

### Actual Result:
Deprecated features used!
  rename source to new_resource.source at 1 location:
    - c:/windows/temp/packer-chef-solo/local-mode-cache/cache/cookbooks/windows/resources/zipfile.rb:36:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.

**Comment by tas50** [comment]
Looks like this was fixed up recently. Give the latest version a try
