### ISSUE TITLE
Advanced sharing permissions are not set

### ISSUE THREAD

**Issue by whyte624** [chef-cookbooks/windows#513]
### Cookbook version
3.4.0

### Chef-client version
13.6.4

### Platform Details
WIndows Server 2012R2 

### Scenario:
Creating windows share with 

```
  windows_share name do
    action :create
    path path
    full_users ["BUILTIN\\Administrators"]
  end
```

### Expected Result:
In Server manager and Advanced sharing permission Full access for Administrators

### Actual Result:
Server manager permissions - fine
Advanced sharing permissions on directory has only Read access for Everyone.

**Comment by baurzhan-konurbayev** [comment]
Should be fixed here https://github.com/chef-cookbooks/windows/pull/515
