### ISSUE TITLE
windows_share does not grant users full access permissions

### ISSUE THREAD

**Issue by troyready** [chef-cookbooks/windows#516]
### Cookbook version
3.4.1

### Chef-client version
12.19.36

### Platform Details
Windows 2012 R2 AWS AMI

### Scenario:
Use the windows_share resource to create a share granting full access to specific local users

### Steps to Reproduce:
Use the windows_share resource with local users specified:

```
windows_share 'myshare' do
  path 'C:\myfolder\myshare'
  full_users %w(.\localuser1 .\anotherlocaluser)
end
```

### Expected Result:
A share with the local users defined as having full access.

### Actual Result:
The resource converges cleanly, but the access permissions don't include the users.

inspec test:
```
# Ensure windows share is present with expected (Full Access aka 0) permissions
get_share_perms =
  'Get-SmbShareAccess -Name myshare | Select-Object -Property AccountName, AccessRight | ConvertTo-Json -Compress'
describe powershell(get_share_perms) do
  its('stdout') { should match /"AccountName":"[-A-Za-z0-9]*\\\\localuser1","AccessRight":0/ }
  its('stdout') { should match /"AccountName":"[-A-Za-z0-9]*\\\\anotherlocaluser","AccessRight":0/ }
end
```

test-kitchen output:
```
  Powershell stdout
     ∅  should match /"AccountName":"[-A-Za-z0-9]*\\\\localuser1","AccessRight":0/
     expected "{\"AccountName\":\"Everyone\",\"AccessRight\":0}\r\n" to match /"AccountName":"[-A-Za-z0-9]*\\\\localuser1","AccessRight":0/
     Diff:
     @@ -1,2 +1,2 @@
     -/"AccountName":"[-A-Za-z0-9]*\\\\localuser1","AccessRight":0/
     +{"AccountName":"Everyone","AccessRight":0}
     
     ∅  should match /"AccountName":"[-A-Za-z0-9]*\\\\anotherlocaluser","AccessRight":0/
     expected "{\"AccountName\":\"Everyone\",\"AccessRight\":0}\r\n" to match /"AccountName":"[-A-Za-z0-9]*\\\\anotherlocaluser","AccessRight":0/
     Diff:
     @@ -1,2 +1,2 @@
     -/"AccountName":"[-A-Za-z0-9]*\\\\anotherlocaluser","AccessRight":0/
     +{"AccountName":"Everyone","AccessRight":0}
```

**Comment by troyready** [comment]
This is essentially re-opening #501 since the issue is still present for me. Feel free to close this and re-open #501 instead if that would be more appropriate.

For anyone else affected by this in the meantime, I'm working around it by just using PS:
```
unless ::File.directory? 'c:/myfolder/myshare' # ~FC023
  powershell_script 'add_myshare_share' do
    code 'New-SmbShare -Name "myshare" '\
         '-Path "C:\myfolder\myshare" '\
         '-FullAccess "localuser1", "anotherlocaluser"'
  end
end
```

**Comment by fourth-barryleonard** [comment]
Issue is still present for me also

**Comment by tas50** [comment]
I think the real solution for this resource is to rewrite it using PS since the full set of options on the share are available there. It would probably be a lot faster as well.

**Comment by tas50** [comment]
I did the first part of the powershell rewrite last night before I realized it was going to take a bit longer. We now create/delete the shares using powershell. The share permission stuff is the hard part and it's going to require a bit of parsing of the PS output along with some logic to determine when we need to use PS to update the perms. I suspect I'll get that working post Chef 14 and then we should have a resource that's ready to merge into core Chef for Chef 15

**Comment by tas50** [comment]
I've merged in the powershell rewrite. I'm fairly certain there's some edge cases I haven't though out, but considering the state of the previous resource I'm going to ship what I have. It's all powershell, includes a bunch of new properties, and seems to properly handle permissions.
