### ISSUE TITLE
Strange warning appears on kitchen converge after last update (3.5.0)

### ISSUE THREAD

**Issue by nicutor** [chef-cookbooks/windows#529]
### Cookbook version
3.5.0

### Chef-client version
Chef: 13.6.4

### Platform Details
centos-7

### Scenario:
-

### Steps to Reproduce:
Executing kitchen converge

### Expected Result:
No warnings

### Actual Result:
```
Installing Cookbook Gems:
Compiling Cookbooks...
/tmp/kitchen/cache/cookbooks/windows/resources/font.rb:25: warning: regex literal in condition
Converging 6 resources
```

I guess this warning should not be there at all.
Can you please check?

**Comment by tas50** [comment]
@nicutor Can you try 3.5.1. I'm fairly certain I just fixed that by accident.

**Comment by nicutor** [comment]
@tas50 the warning seems to be gone on 3.5.1

Thank you.

**Comment by tas50** [comment]
Good to hear. Thanks for the report
