### ISSUE TITLE
Bug installing .Net 3 from source using windows_feature_dism

### ISSUE THREAD

**Issue by josh-barker** [chef-cookbooks/windows#540]
### Cookbook version
4.0.1

### Chef-client version
12.22.1

### Platform Details
Windows 2012R2

### Scenario:
I'm trying to install .Net Framework versions 3.5 from source

### Steps to Reproduce:
```
windows_feature 'install .Net Framework versions: 3.5, 3.0 & 2.0' do
  feature_name 'NetFx3'
  source 'C:\temp\sxs'
  action :install
  all true
end
```

### Expected Result:
`NetFx3` is installed

### Actual Result:
It says that its already installed.
```
windows_feature[install .Net Framework versions: 3.5, 3.0 & 2.0] action install[2018-03-14T13:55:18+11:00] INFO: Processing windows_feature[install .Net Framework versions: 3.5, 3.0 & 2.0] action install (test_windows::default line 34)
       
           * windows_feature_dism[install .Net Framework versions: 3.5, 3.0 & 2.0] action install[2018-03-14T13:55:18+11:00] INFO: Processing windows_feature_dism[install .Net Framework versions: 3.5, 3.0 & 2.0] action install (C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/windows/resources/feature.rb line 47)
        (up to date)
            (up to date)
```

However, `dism /Get-Features /Online /Format:Table /English` shows
```
...
NetFx3  | Disabled with Payload Removed
...
```

### Other observations:
`features_to_install` does the intersection of what is asked for and `node['dism_features_cache']['disabled']` (See https://github.com/chef-cookbooks/windows/blob/master/resources/feature_dism.rb#L83)
  * Since `NetFx3` is in `node['dism_features_cache']['removed']`, its not installed.
  * I think the intersection should be between what is asked for, and the combination of `node['dism_features_cache']['disabled']` and `node['dism_features_cache']['removed']`

Also, I noticed that `all_available` is defined differently in 2 places:
  * https://github.com/chef-cookbooks/windows/blob/master/resources/feature_dism.rb#L96
  * https://github.com/chef-cookbooks/windows/blob/master/resources/feature_dism.rb#L109

**Comment by perithompson** [comment]
Having the same problem on Server 2016 after upgrading to the latest version. this was working fine on version 3

**Comment by tas50** [comment]
Looks like I handled the source scenario correctly in the method that fails if unavailable, but then I missed it entirely when I calculated the list of features to install. I don't actually have a windows system in a state where I can fully test this so I'm hoping that someone can give this code a try to see if it correctly installs removed features when specifying the source.

https://github.com/chef-cookbooks/windows/pull/541

**Comment by perithompson** [comment]
@tas50 Tested this on Windows server 2016 and .net 3.5sp1 installs fine with DISM now.

**Comment by tas50** [comment]
Perfect. Thanks for checking. I'll get this released right now and I already opened a PR to make sure the version in Chef 14 has this fix.
