### ISSUE TITLE
windows_feature_powershell features are now case sensitive

### ISSUE THREAD

**Issue by mccw** [chef-cookbooks/windows#545]
### Cookbook version
4.1.x

### Chef-client version
13.8.5

### Platform Details
Server 2016

### Scenario:
I'm using windows_feature with powershell to install roles and features. Since 4.1.x the step fails with:  RuntimeError: The Windows feature Web-ASP-Net45 is not available on this version of Windows. Run 'Get-WindowsFeature' to see the list of available feature names.

### Steps to Reproduce:
This installs correctly in version 4.0.2 and still works if I roll the cookbook back to that version.

### Expected Result:
Install Web-ASP-Net45

### Actual Result:
https://gist.github.com/mccw/cd878d48c8ee747c298380a18286b216

**Comment by jakauppila** [comment]
What is the output of `Get-WindowsFeature`?

**Comment by mccw** [comment]
That was the first thing I checked. This is after having installed features with version 4.0.2 of the windows cookbook:

https://gist.github.com/mccw/3db5d6b8f928786c10a91128d80c429d

**Comment by mccw** [comment]
It does appear to be a case issue. I renamed Web-ASP-Net45 to Web-Asp-Net45 and it failed on other services that don't match case. Now that I know how to fix it I can but this wasn't an issue prior to 4.1.0.

**Comment by tas50** [comment]
I renamed this issue. I'll see if I can get the case sensitivity fixed. This wasn't an issue before because we didn't really do any input validation and we didn't fail if the feature wasn't there. Now we actually validate that the feature exists so we can properly fail if you typo a feature instead of continuing on. I didn't consider this part of that validation.

**Comment by jakauppila** [comment]
I would assume DISM is similarly affected?

**Comment by tas50** [comment]
It's roughly the same logic so they both probably have the same issue. I think the solution is probably to downcase the available feature name ans the provided names so when we do the array comparisons it all works out. We just have to make sure dism also doesn't care about case on the CLI

**Comment by mccw** [comment]
Thanks for taking the time to look at this.

 I fixed my issues by matching the Microsoft case. ...which isn't consistent by the way.

**Comment by tas50** [comment]
MS is all over the place with the names

**Comment by amcappelli** [comment]
I saw that 4.1.2 was released to fix this, but when testing with it I am finding that DISM is case-sensitive on Windows 2008 R2, so when the feature is forced to lowercase DISM fails to find it. It does work correctly on Windows 2012 R2.

https://gist.github.com/amcappelli/dcf977ba855b07ecb57db7ddc740945a

**Comment by tas50** [comment]
I put some logic in the dism side to make sure we don't downcase the features when we're on Windows 2008 R2.
