### ISSUE TITLE
Backward compatible metadata

### ISSUE THREAD

**Issue by s1mark** [chef-cookbooks/windows#546]
### Cookbook version
4.1.1

### Chef-client version
Irrelevant

### Platform Details
Chef Server 11

### Scenario:
Uploading cookbook to old versions of chef-server (11)

### Actual Result:
Chef Server does not understand issue_url and source_url in the metadata

### Possible solution
```ruby
source_url       'https://github.com/chef-cookbooks/windows' if respond_to?(:source_url)
issues_url       'https://github.com/chef-cookbooks/windows/issues' if respond_to?(:issue_url)
```

**Comment by tas50** [comment]
This cookbook requires Chef 12.7 or later and Chef 11 hasn't been a supported release of Chef for about a year now. If you need Chef 11 support you'll need to install an older version of this cookbook since none of the resources will run on Chef 11 either.

**Comment by s1mark** [comment]
@tas50  by 

> Chef 12.7
you mean chef-client or chef-server?  We have issues uploading to chef-server not with running the chef-client cookbook

**Comment by s1mark** [comment]
@tas50 
So by Chef 12.7 you meant chef version on the Chef Wokrstation. After I have updated the ChefDK on the Chef Workstation it uploaded correctly
