### ISSUE TITLE
windows_share broken on server 2008

### ISSUE THREAD

**Issue by FireEater64** [chef-cookbooks/windows#551]
### Cookbook version
4.2.1

### Chef-client version
12.18.31

### Platform Details
Server 2008 R2

### Scenario:
Create a fileshare using `windows_share`

### Steps to Reproduce:
Converge the following on Server 2008 R2

```ruby
windows_share 'Test' do
  path 'C:/temp'
  read_users ['Administrators']
  description 'Test share'
end
```

### Expected Result:
'Test' share created

### Actual Result:
Since the `New-SmbShare` cmdlet was only introduced in server 2012, switching `windows_share` to use powershell (#531) has broken share creation on Server 2008

```powershell
New-SmbShare : The term 'New-SmbShare' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I'm aware this might not get fixed (not sure what the timeline is for this cookbook continuing to support Server 2008) - but at least a note in the documentation would be nice. Versions of the cookbook prior to the changes introduced by #531 (v3.5.1) still work on 2008.

**Comment by tas50** [comment]
I added better error messaging and a readme note in 4.2.2. The resource really had to go to powershell since the existing WMI based behavior was broken for permissions everywhere and didn't work on Windows 2016. Thanks for the report though. This should have gone out in the initial release.
