### ISSUE TITLE
Powershell scripts fails during bootstrap but works post first chef-client run

### ISSUE THREAD

**Issue by AnishAnil** [chef-cookbooks/windows#554]
I have the below recipe which executes a power shell command:

```
powershell_script 'Install' do
    cwd 'C:\scripts'
    code <<-EOH
    powershell C:\\scripts\\pair.ps1 -repo-host #{repohost} -repo-dir #{repodir} -repo-https-port #{repohttpsport} -management-server #{managementserver} -activation-code #{activationcode} -env #{env} -loc #{loc} -role #{role} -app #{app}; Set-ExecutionPolicy -Scope process undefined -Force;
    EOH
end
```

The recipe basically downloads a pair.sh file from the internet and stores it in the c:\scripts directory. This is achieved in the first part of the cookbook.

During the bootstrap it is added to the node and post bootstrap it runs the chef-client as part of the botstrap and it fails with the below errors:

```
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com Error executing action run on resource 'powershell_script[Insta ll]'
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com =================================================================

ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ec2-13-232-54-174.ap-south-1.compute.amazonaws.com **

    Mixlib::ShellOut::ShellCommandFailed

** ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ------------------------------------ ec2-13-232-54-174.ap-south-1.compute.amazonaws.com Expected process to exit with [0], but received '1' ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ---- Begin output of "powershell.exe" -NoLogo -NonInteractive -No Profile -ExecutionPolicy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_scri pt-user-code20180502-2840-7o4rwn.ps1'" ---- ec2-13-232-54-174.ap-south-1.compute.amazonaws.com STDOUT: ec2-13-232-54-174.ap-south-1.compute.amazonaws.com STDERR: Thread failed to start. ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ---- End output of "powershell.exe" -NoLogo -NonInteractive -NoPr ofile -ExecutionPolicy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script -user-code20180502-2840-7o4rwn.ps1'" ---- ec2-13-232-54-174.ap-south-1.compute.amazonaws.com Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -Executio nPolicy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-user-code20180 502-2840-7o4rwn.ps1'" returned 1 ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-02T17:49:46+00:00] FATAL: Mixlib::ShellOut::ShellCommandFail ed: powershell_script[Install] (illumio2::default line 39) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1' ERROR: Failed to execute command on ec2-13-232-54-174.ap-south-1.compute.amazonaws.com return code 1 ERROR: Bootstrap command returned 1
```

Once the bootstrap fails, when i manually run the chef-clinet run on this node this completes successfully.

It is a strange behavior that it fails during bootstrap but the same command works on the first chef-client run

Any leads on fixing this error is greatly appreciated

```
chef-client version:
 chef_version=14.0.202
 platform=windows
 platform_version=6.1.7601
 ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
 program_name=C:/opscode/chef/bin/chef-client
 executable=C:/opscode/chef/bin/chef-client
```

**Comment by AnishAnil** [comment]
It is the exact same error:

**********
knife winrm -m ec2-13-232-54-174.ap-south-1.compute.amazonaws.com chef-client -x 'Administrator' -P '''password'''
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com       domain nil
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com       user nil
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com     end
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com     System Info:
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com     ------------
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com     chef_version=14.0.202
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com     platform=windows
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com     platform_version=6.1.7601
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com     ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com     program_name=C:/opscode/chef/bin/chef-client
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com     executable=C:/opscode/chef/bin/chef-client
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:50+00:00] INFO: Running queued delayed notification
s before re-raising exception
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:50+00:00] INFO: Running queued delayed notification
s before re-raising exception
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com Running handlers:
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:50+00:00] ERROR: Running exception handlers
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:50+00:00] ERROR: Running exception handlers
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com Running handlers complete
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:50+00:00] ERROR: Exception handlers complete
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:50+00:00] ERROR: Exception handlers complete
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com Chef Client failed. 0 resources updated in 08 seconds
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:50+00:00] INFO: Sending resource update report (run
-id: b868d27b-0e52-4e35-8571-e6f52c8c8b5e)
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:50+00:00] INFO: Sending resource update report (run
-id: b868d27b-0e52-4e35-8571-e6f52c8c8b5e)
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:51+00:00] FATAL: Stacktrace dumped to c:/chef/cache
/chef-stacktrace.out
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:51+00:00] FATAL: Stacktrace dumped to c:/chef/cache
/chef-stacktrace.out
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:51+00:00] FATAL: Please provide the contents of the
 stacktrace.out file if you file a bug report
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:51+00:00] FATAL: Please provide the contents of the
 stacktrace.out file if you file a bug report
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:51+00:00] FATAL: Mixlib::ShellOut::ShellCommandFail
ed: powershell_script[Install] (illumio2::default line 39) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected
process to exit with [0], but received '1'
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProf
ile -ExecutionPolicy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-u
ser-code20180503-2704-129u6uw.ps1'" ----
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com STDOUT:
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com STDERR: Thread failed to start.
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfil
e -ExecutionPolicy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-use
r-code20180503-2704-129u6uw.ps1'" ----
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPol
icy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-user-code20180503-
2704-129u6uw.ps1'" returned 1
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T05:22:51+00:00] FATAL: Mixlib::ShellOut::ShellCommandFail
ed: powershell_script[Install] (illumio2::default line 39) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected
process to exit with [0], but received '1'
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProf
ile -ExecutionPolicy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-u
ser-code20180503-2704-129u6uw.ps1'" ----
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com STDOUT:
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com STDERR: Thread failed to start.
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfil
e -ExecutionPolicy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-use
r-code20180503-2704-129u6uw.ps1'" ----
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPol
icy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-user-code20180503-
2704-129u6uw.ps1'" returned 1
ERROR: Failed to execute command on ec2-13-232-54-174.ap-south-1.compute.amazonaws.com return code 1
**********

Kindly note: The recipe works fine if i push it manually to the node using the CHEF Server UI and then login to the node machine and run a chef-client command.

It only fails if i bootstrap and run the recipe during the initial bootstrap command itself

**Comment by AnishAnil** [comment]
Further Testing:

On the Node machine create a powershell script file with the following contents:

**********
Write-Host "Hello, World!"
**********
Create a new recipe with the following data

**********
#
# Cookbook:: powershell
# Recipe:: default
#
# Copyright:: 2018, The Authors, All Rights Reserved.
powershell_script 'Install' do
    cwd 'C:\\scripts'
    #code <<-EOH
    command powershell C:\\scripts\\script.ps1
    #EOH
end
**********
It fails with similar errors:

************
ed: powershell_script[Install] (powershell::default line 6) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected
 process to exit with [0], but received '1'
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProf
ile -ExecutionPolicy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-u
ser-code20180503-2180-flt8gf.ps1'" ----
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com STDOUT:
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com STDERR: Thread failed to start.
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com ---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfil
e -ExecutionPolicy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-use
r-code20180503-2180-flt8gf.ps1'" ----
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPol
icy Bypass -InputFormat None -Command ". 'C:/Users/ADMINI~1/AppData/Local/Temp/chef_powershell_script-user-code20180503-
2180-flt8gf.ps1'" returned 1
ec2-13-232-54-174.ap-south-1.compute.amazonaws.com [2018-05-03T06:43:33+00:00] FATAL: Mixlib::ShellOut::ShellCommandFail
ed: powershell_script[Install] (powershell::default line 6) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected
 process to exit with [0], but received '1'
************

Now if the same is run using chef-client it completes successfully.

************
PS C:\scripts> chef-client
Starting Chef Client, version 14.0.202
[2018-05-03T06:39:38+00:00] INFO: *** Chef 14.0.202 ***
[2018-05-03T06:39:38+00:00] INFO: Platform: x64-mingw32
[2018-05-03T06:39:38+00:00] INFO: Chef-client pid: 1316
[2018-05-03T06:39:38+00:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
[2018-05-03T06:39:43+00:00] INFO: Run List is [recipe[powershell::default]]
[2018-05-03T06:39:43+00:00] INFO: Run List expands to [powershell::default]
[2018-05-03T06:39:43+00:00] INFO: Starting Chef Run for Web712
[2018-05-03T06:39:43+00:00] INFO: Running start handlers
[2018-05-03T06:39:43+00:00] INFO: Start handlers complete.
[2018-05-03T06:39:44+00:00] INFO: Error while reporting run start to Data Collector. URL: https://api.chef.io/organizati
ons/anish_chef/data-collector Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)
resolving cookbooks for run list: ["powershell::default"]
[2018-05-03T06:39:45+00:00] INFO: Loading cookbooks [powershell@0.1.0]
Synchronizing Cookbooks:
  - powershell (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: powershell::default
  * powershell_script[Install] action run[2018-05-03T06:39:46+00:00] INFO: Processing powershell_script[Install] action
run (powershell::default line 6)

    [execute] Hello, World!
[2018-05-03T06:39:47+00:00] INFO: powershell_script[Install] ran successfully
    - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionP
olicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/2/chef-script20180503-1316-1q1z7nh.ps1"
[2018-05-03T06:39:48+00:00] INFO: Chef Run complete in 5.3548 seconds

Running handlers:
[2018-05-03T06:39:48+00:00] INFO: Running report handlers
Running handlers complete
[2018-05-03T06:39:48+00:00] INFO: Report handlers complete
Chef Client finished, 1/1 resources updated in 10 seconds
[2018-05-03T06:39:48+00:00] INFO: Sending resource update report (run-id: 15af24c1-7a04-439d-9d15-5a0f8b810097)
PS C:\scripts>
**********************

Is this some kind of defect or wrong execution method that is being used in this recipe??

Thank you

**Comment by tas50** [comment]
I believe this is actually a chef-client issues since powershell_script is part of core chef. You'll want to file this issue here if you're still having the issue: https://github.com/chef/chef/issues/new
