### ISSUE TITLE
windows_share resource in cookbook v4.2.2 doesn't handle server platform_version correctly

### ISSUE THREAD

**Issue by smastrorocco** [chef-cookbooks/windows#556]
### Cookbook version
4.2.2

### Chef-client version
14.1.1

### Platform Details
Windows Server 2012 R2

### Scenario:
Use windows_share resource

### Steps to Reproduce:
Declare a windows_share resource on Windows Server 2012 R2 with cookbook v4.2.2

### Expected Result:
Windows share to be created.

### Actual Result:
Error that resource is only supported on Windows 8/12.

Resource is not considering correct platform_version for Windows Server: `"platform_version": "6.3.9600"`
```ruby
if node['platform_version'].to_f < 8.2
```

https://github.com/chef-cookbooks/windows/blob/v4.2.2/resources/share.rb#L117

**Comment by tas50** [comment]
This should be fixed in 4.2.4. Thanks for the report.
