### ISSUE TITLE
Feature Request: printer resource should have the ability to set a default paper size

### ISSUE THREAD

**Issue by kmf** [chef-cookbooks/windows#560]
### Cookbook version
4.2.2

### Platform Details
Windows 10

### Scenario:
would like the ability to set a default paper size when I configure a printer
some thing like 
```
windows_printer 'Magic Printer' do
  driver_name 'HP LaserJet 500 color MFP M570 PCL6 Class Driver'
  location 'Basement'
  ipv4_address '10.0.0.10'
  papersize 'A4'
end
```

### Current work around is in PowerShell
```
windows_printer 'MagicPrinter' do
  driver_name 'HP LaserJet 500 color MFP M570 PCL6 Class Driver'
  location 'Basement'
  ipv4_address '10.0.0.10'
  action :create
  notifies :run, 'powershell_script[Set_Papersize_MagicPrinter_to_A4]'  
end
```
```
powershell_script 'Set_Papersize_MagicPrinter_to_A4' do
  code <<-EOH
  Set-PrintConfiguration -PaperSize A4 -PrinterName MagicPrinter
  EOH
end
```

**Comment by tas50** [comment]
@kmf Now that this resource is in Chef Infra Client itself we're not going to be further expanding upon it here. I think there's a lot we could do with the printer resources to make them more usable and this is a great example. Can you file this issue in the chef/chef repo please?

**Comment by kmf** [comment]
Done.

@tas50 https://github.com/chef/chef/issues/9674

**Comment by tas50** [comment]
Thanks @kmf
