### ISSUE TITLE
windows_share

### ISSUE THREAD

**Issue by ckoenig673** [chef-cookbooks/windows#562]
### Cookbook version
[4.3.0]

### Chef-client version
[Chef 13.2.20]

### Platform Details
[Windows 2012. Amazon]

### Scenario:
[Trying to add a share with multiple users in the string array]

### Steps to Reproduce:
[created a share step]
windows_share "share" do
  action :create
  path "C:\\share"
  full_users ["domain\\resource1", "domain\\resource2"]
end

### Expected Result:
[Expecting a share to be created with two domain resources with full access to the share.]

### Actual Result:
[Chef script errors out.  The issue is that the each string object is not getting quoted properly.]

---- Begin output of powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command "Grant-SmbShareAccess -Name 'root' -AccountName \"domain\resource1,domain\resource2\" -Force -AccessRight full" ----
STDOUT: 
STDERR: Grant-SmbShareAccess : No mapping between account names and security IDs was 
done. 
At line:1 char:1
+ Grant-SmbShareAccess -Name 'root' -AccountName "domain\resource1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_SmbShare (...copeName = "*") 
   :ROOT/Microsoft/Windows/SMB/MSFT_SMBShare) [Grant-SmbShareAccess], CimExce  
  ption
    + FullyQualifiedErrorId : Windows System Error 1332,Grant-SmbShareAccess
---- End output of powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command "Grant-SmbShareAccess -Name 'root' -AccountName \"cof\resource1,cof\resource2\" -Force -AccessRight full" ----
Ran powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command "Grant-SmbShareAccess -Name 'root' -AccountName \"cof\resource1,cof\resource2\" -Force -AccessRight full" returned 1

**Comment by tas50** [comment]
I pushed a fix in 4.3.1 and added a kitchen test for this. Feel free to open this back up if you're still having issues.

**Comment by ckoenig673** [comment]
I retested and it is working.  --thanks
