### ISSUE TITLE
windows_feature_powershell resource fails on PowerShell 3.0

### ISSUE THREAD

**Issue by p0rkjello** [chef-cookbooks/windows#563]
### Cookbook version
4.3.2

### Chef-client version
13.9.4

### Platform Details
Windows 2008 R2, PowerShell 3.0

### Scenario:
Install Windows Feature w/ windows_feature_powershell install method

### Steps to Reproduce:
```
windows_feature 'RDS-RD-Server' do
  action :install
  install_method :windows_feature_powershell
end
```

### Expected Result:
Feature is installed

### Actual Result:
Error executing action `install` on resource 'windows_feature[RDS-RD-Server]'
     
     RuntimeError
     windows_feature_powershell[RDS-RD-Server] (c:/chef/cache/cookbooks/windows/resources/feature.rb line 47) had an error: RuntimeError: The windows_feature_powershell resource requires PowerShell 3.0 or later. Please install PowerShell 3.0+ before running this resource.

### Notes:

I believe there is a typo in feature_powershell.rb. Should read `['languages']['powershell']['version'].to_i >= 3`

```
def raise_on_old_powershell
    # be super defensive about the powershell lang plugin not being there
    return if node['languages'] && node['languages']['powershell'] && node['languages']['powershell']['version'].to_i > 3
    raise 'The windows_feature_powershell resource requires PowerShell 3.0 or later. Please install PowerShell 3.0+ before running this resource.' if powershell_version < 3
  end
```

**Comment by tas50** [comment]
Fixed in 4.3.3. Thanks for the report
