### ISSUE TITLE
Certificate being installed in the wrong store's environment.

### ISSUE THREAD

**Issue by ckoenig673** [chef-cookbooks/windows#566]
### Cookbook version
[4.3.1]

### Chef-client version
[13.2.20]

### Platform Details
[Windows 2012]

### Scenario:
[When using the windows_certificate package, the certificate is not being added to the local computer store.  It is always being added to the user store]

### Steps to Reproduce:
[windows_certificate "D:/support/pfxfilename.pfx" do
    store_name    "MY"
    pfx_password    "pfxpassword"
    user_store false
end]

### Expected Result:
[I am expecting the certificate be installed in the personal local computer store vs the user store]

### Actual Result:
[Certificate is installed in the local user store.]

**Comment by piyushawasthi** [comment]
Hi @ckoenig673 : This issue fixed in PR: https://github.com/chef/win32-certstore/pull/37

**Comment by silverl** [comment]
Just hit this myself. Looking forward to the merge/release.

**Comment by tas50** [comment]
Still an issue with the latest code

**Comment by btm** [comment]
@silverl can you confirm what version of the `win32-certstore` gem is on this system?
```
C:\opscode\chef\embedded\bin\gem.bat list win32-certstore
```

It needs to be 0.1.7 which was released yesterday. I'm not sure that the cookbook necessarily would update it, it looks like the `chef_gem` resource in the windows cookbook is using the `:install` action and not the `:upgrade` action.

**Comment by silverl** [comment]
Hmm, I'm getting an empty list back. I'm using ChefDK so I changed the path to embedded.

```
PS C:\> C:\opscode\chefdk\embedded\bin\gem.bat list win32-certstore

*** LOCAL GEMS ***
``` 

I use Policyfiles, if that makes a difference.

**Comment by btm** [comment]
@silverl how are you running chef-client? running `chef-client` out of `C:\opscode\chefdk\bin` directly, or using a scheduled task, or using chef-apply, or? Can you share the whole command you're running for clarity?

**Comment by silverl** [comment]
Yes, running `chef-client` directly, on a new VM after a fresh provisioning using `knife bootstrap windows winrm`.

**Comment by btm** [comment]
@silverl oh, `knife bootstrap` should be installing the Chef Client on that VM, it's that install of chef-client that we're interested in, not one on your workstation that you're booting with. Can you run `C:\opscode\chef\embedded\bin\gem.bat list win32-certstore` on that system?

**Comment by silverl** [comment]
Came back with `win32-certstore (0.1.3)`

**Comment by tas50** [comment]
This will be fixed by the new version of the Windows cookbook that ships today.
