### ISSUE TITLE
undefined method `win_friendly_path' for #<#<Class:0x0000000004220908>:0x0000000007eb5cd8>

### ISSUE THREAD

**Issue by mccw** [chef-cookbooks/windows#583]
### Cookbook version
5.1.3

### Chef-client version
14.5.33

### Platform Details
System Info:
chef_version=14.5.33
platform=windows
platform_version=10.0.14393
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
program_name=C:/opscode/chef/bin/chef-client
executable=C:/opscode/chef/bin/chef-client

### Scenario:
trying to acl_add an existing certificate.

### Steps to Reproduce:
windows_certificate 'C:\temp\star_bowl_com.pfx' do
  pfx_password vault['star_bowl_com']
  private_key_acl ['NT AUTHORITY\NETWORK SERVICE']
  action [:create, :acl_add]
end

The create step is skipping due to 'up to date' which is correct
the acl_add step is failing due to 'undefined method `win_friendly_path' for #<#<Class:0x0000000004220908>:0x0000000007eb5cd8>'

### Expected Result:
acl_add should also skip due to being 'up to date'

### Actual Result:
chef-client  fails

**Comment by jugatsu** [comment]
https://github.com/chef-cookbooks/windows/commit/35baf2085fb6a5f2e7977d5bbf203f14860c6a56 breaks `windows_certificate` resource.

**Comment by tas50** [comment]
This was fixed by https://github.com/chef-cookbooks/windows/pull/589 and that was released in 5.1.6
