### ISSUE TITLE
Windows Certificate -> Does not store private key

### ISSUE THREAD

**Issue by xorima** [chef-cookbooks/windows#599]
### Cookbook version
5.2.2

### Chef-client version
13.9.4

### Platform Details
Server 2016

### Scenario:
Install certificate with private key

### Steps to Reproduce:
Try to install a certificate with a private key:

```
  windows_certificate 'cert.example.com' do
    pfx_password      'password'
    private_key_acl   'BUILTIN\\USERS'
  end
```

### Expected Result:
certificate and private key is installed and is visible in mmc for local computer

### Actual Result:
Certificate is installed but private key is not.

**Comment by SteveLowe** [comment]
We're seeing the same problem, it looks like when the certificate resource was re-written to pull it into chef (7304dcb), it lost the ability to import private keys.

This worked fine for us with chef client 14.2.0 and windows cookbook 4.1.4
It doesn't work with chef-client 14.8.2 and windows cookbook 5.2.2

I will log a bug in https://github.com/chef/chef as that is where windows_certificate has been moved to.

**Comment by Xorima** [comment]
It is currently in both I am seeing, also have opened up a PR here with all the tests which should cover everyones use cases? https://github.com/chef-cookbooks/windows/pull/600
