### ISSUE TITLE
Remove windows_share and windows_certificate resources

### ISSUE THREAD

**Issue by btm** [chef-cookbooks/windows#623]
https://github.com/chef-cookbooks/windows#deprecated-resources-note

We moved `windows_share` and `windows_certificate` into core for Chef 14.7. We had announced we would remove those from this cookbook late last year but didn't get to it. Let's remove them now and ship a v7 of this cookbook. 

Chef 14 will be EOL in 6 weeks. Probably we  should bump the minimum version of Chef to 15 too.

This also will allow us to remove `win32-certstore` as a gem dependency on this cookbook.

**Comment by Xorima** [comment]
Note: Remember to remove the deprecated path helper when a v7 is released.
