### ISSUE TITLE
Install MSI for ALLUSERS by default

### ISSUE THREAD

**Issue by dopuskh3** [chef-cookbooks/windows#97]
When a MSI does not install for all users by default, it is only installed for the user that runs chef-client.

Installing windows package for all users by default is a reasonable default and is consistent with the way it's done on other plaforms.

**Comment by tas50** [comment]
We've removed the windows_package provider in this cookbook in favor of the package provider that is built into chef now. I'm going to close this issue out. If you're still seeing the problem with that modernized code please open an issue up against chef/chef.
